import type { League, LeagueInfo, Jersey } from '../types';

export const leagues: LeagueInfo[] = [
  { id: 'selecciones', name: { en: 'National Teams', es: 'Selecciones' }, country: 'INTL' },
  { id: 'la-liga', name: { en: 'La Liga', es: 'La Liga' }, country: 'ES' },
  { id: 'premier-league', name: { en: 'Premier League', es: 'Premier League' }, country: 'GB' },
  { id: 'serie-a', name: { en: 'Serie A', es: 'Serie A' }, country: 'IT' },
  { id: 'bundesliga', name: { en: 'Bundesliga', es: 'Bundesliga' }, country: 'DE' },
  { id: 'ligue-1', name: { en: 'Ligue 1', es: 'Ligue 1' }, country: 'FR' },
  { id: 'brasileirao', name: { en: 'Brasileirão', es: 'Brasileirão' }, country: 'BR' },
  { id: 'retro', name: { en: 'Retro', es: 'Retro' }, country: 'INTL' },
  { id: 'resto-de-ligas', name: { en: 'Rest of the World', es: 'Resto del Mundo' }, country: 'INTL' },
];

export const jerseys: Jersey[] = [
  // La Liga - Real Madrid
  {
    id: 'real-madrid-1',
    team: 'Real Madrid',
    league: 'la-liga',
    price: 35.99,
    originalPrice: 109.99,
    image: '/images/la-liga/real-madrid/1/1.jpg',
    images: [
      '/images/la-liga/real-madrid/1/1.jpg',
      '/images/la-liga/real-madrid/1/2.jpg',
      '/images/la-liga/real-madrid/1/3.jpg',
      '/images/la-liga/real-madrid/1/4.jpg',
      '/images/la-liga/real-madrid/1/5.jpg',
    ],
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'real-madrid-2',
    team: 'Real Madrid',
    league: 'la-liga',
    price: 35.99,
    image: '/images/la-liga/real-madrid/2/1.jpg',
    images: [
      '/images/la-liga/real-madrid/2/1.jpg',
      '/images/la-liga/real-madrid/2/2.jpg',
      '/images/la-liga/real-madrid/2/3.jpg',
      '/images/la-liga/real-madrid/2/4.jpg',
      '/images/la-liga/real-madrid/2/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'real-madrid-3',
    team: 'Real Madrid',
    league: 'la-liga',
    price: 35.99,
    image: '/images/la-liga/real-madrid/3/1.jpg',
    images: [
      '/images/la-liga/real-madrid/3/1.jpg',
      '/images/la-liga/real-madrid/3/2.jpg',
      '/images/la-liga/real-madrid/3/3.jpg',
      '/images/la-liga/real-madrid/3/4.jpg',
      '/images/la-liga/real-madrid/3/5.jpg',
      '/images/la-liga/real-madrid/3/6.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },

  // La Liga - FC Barcelona
  {
    id: 'barcelona-1',
    team: 'FC Barcelona',
    league: 'la-liga',
    price: 35.99,
    originalPrice: 109.99,
    image: '/images/la-liga/barcelona/1/1.jpg',
    images: [
      '/images/la-liga/barcelona/1/1.jpg',
      '/images/la-liga/barcelona/1/2.jpg',
      '/images/la-liga/barcelona/1/3.jpg',
      '/images/la-liga/barcelona/1/4.jpg',
      '/images/la-liga/barcelona/1/5.jpg',
    ],
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'barcelona-2',
    team: 'FC Barcelona',
    league: 'la-liga',
    price: 35.99,
    image: '/images/la-liga/barcelona/2/1.jpg',
    images: [
      '/images/la-liga/barcelona/2/1.jpg',
      '/images/la-liga/barcelona/2/2.jpg',
      '/images/la-liga/barcelona/2/3.jpg',
      '/images/la-liga/barcelona/2/4.jpg',
      '/images/la-liga/barcelona/2/5.jpg',
      '/images/la-liga/barcelona/2/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'barcelona-3',
    team: 'FC Barcelona',
    league: 'la-liga',
    price: 35.99,
    image: '/images/la-liga/barcelona/3/1.jpg',
    images: [
      '/images/la-liga/barcelona/3/1.jpg',
      '/images/la-liga/barcelona/3/2.jpg',
      '/images/la-liga/barcelona/3/3.jpg',
      '/images/la-liga/barcelona/3/4.jpg',
      '/images/la-liga/barcelona/3/5.jpg',
      '/images/la-liga/barcelona/3/6.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },

  // La Liga - Atlético de Madrid
  {
    id: 'atletico-madrid-1',
    team: 'Atlético de Madrid',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/atletico-madrid/1/1.jpg',
    images: [
      '/images/la-liga/atletico-madrid/1/1.jpg',
      '/images/la-liga/atletico-madrid/1/2.jpg',
      '/images/la-liga/atletico-madrid/1/3.jpg',
      '/images/la-liga/atletico-madrid/1/4.jpg',
      '/images/la-liga/atletico-madrid/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'atletico-madrid-2',
    team: 'Atlético de Madrid',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/atletico-madrid/2/1.jpg',
    images: [
      '/images/la-liga/atletico-madrid/2/1.jpg',
      '/images/la-liga/atletico-madrid/2/2.jpg',
      '/images/la-liga/atletico-madrid/2/3.jpg',
      '/images/la-liga/atletico-madrid/2/4.jpg',
      '/images/la-liga/atletico-madrid/2/5.jpg',
      '/images/la-liga/atletico-madrid/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Real Sociedad
  {
    id: 'real-sociedad-1',
    team: 'Real Sociedad',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/real-sociedad/1/1.jpg',
    images: [
      '/images/la-liga/real-sociedad/1/1.jpg',
      '/images/la-liga/real-sociedad/1/2.jpg',
      '/images/la-liga/real-sociedad/1/3.jpg',
      '/images/la-liga/real-sociedad/1/4.jpg',
      '/images/la-liga/real-sociedad/1/5.jpg',
      '/images/la-liga/real-sociedad/1/6.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },
  {
    id: 'real-sociedad-2',
    team: 'Real Sociedad',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/real-sociedad/2/1.jpg',
    images: [
      '/images/la-liga/real-sociedad/2/1.jpg',
      '/images/la-liga/real-sociedad/2/2.jpg',
      '/images/la-liga/real-sociedad/2/3.jpg',
      '/images/la-liga/real-sociedad/2/4.jpg',
      '/images/la-liga/real-sociedad/2/5.jpg',
      '/images/la-liga/real-sociedad/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Premier League - Manchester City
  {
    id: 'manchester-city-1',
    team: 'Manchester City',
    league: 'premier-league',
    price: 35.99,
    image: '/images/premier-league/manchester-city/1/1.jpg',
    images: [
      '/images/premier-league/manchester-city/1/1.jpg',
      '/images/premier-league/manchester-city/1/2.jpg',
      '/images/premier-league/manchester-city/1/3.jpg',
      '/images/premier-league/manchester-city/1/4.jpg',
      '/images/premier-league/manchester-city/1/5.jpg',
      '/images/premier-league/manchester-city/1/6.jpg',
    ],
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'manchester-city-2',
    team: 'Manchester City',
    league: 'premier-league',
    price: 35.99,
    image: '/images/premier-league/manchester-city/2/1.jpg',
    images: [
      '/images/premier-league/manchester-city/2/1.jpg',
      '/images/premier-league/manchester-city/2/2.jpg',
      '/images/premier-league/manchester-city/2/3.jpg',
      '/images/premier-league/manchester-city/2/4.jpg',
      '/images/premier-league/manchester-city/2/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'manchester-city-3',
    team: 'Manchester City',
    league: 'premier-league',
    price: 35.99,
    image: '/images/premier-league/manchester-city/3/1.jpg',
    images: [
      '/images/premier-league/manchester-city/3/1.jpg',
      '/images/premier-league/manchester-city/3/2.jpg',
      '/images/premier-league/manchester-city/3/3.jpg',
      '/images/premier-league/manchester-city/3/4.jpg',
      '/images/premier-league/manchester-city/3/5.jpg',
      '/images/premier-league/manchester-city/3/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'manchester-city-4',
    team: 'Manchester City',
    league: 'premier-league',
    price: 35.99,
    image: '/images/premier-league/manchester-city/4/1.jpg',
    images: [
      '/images/premier-league/manchester-city/4/1.jpg',
      '/images/premier-league/manchester-city/4/2.jpg',
      '/images/premier-league/manchester-city/4/3.jpg',
      '/images/premier-league/manchester-city/4/4.jpg',
      '/images/premier-league/manchester-city/4/5.jpg',
      '/images/premier-league/manchester-city/4/6.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },

  // Premier League - Arsenal FC
  {
    id: 'arsenal-1',
    team: 'Arsenal FC',
    league: 'premier-league',
    price: 35.99,
    image: '/images/premier-league/arsenal/1/1.jpg',
    images: [
      '/images/premier-league/arsenal/1/1.jpg',
      '/images/premier-league/arsenal/1/2.jpg',
      '/images/premier-league/arsenal/1/3.jpg',
      '/images/premier-league/arsenal/1/4.jpg',
      '/images/premier-league/arsenal/1/5.jpg',
      '/images/premier-league/arsenal/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'arsenal-2',
    team: 'Arsenal FC',
    league: 'premier-league',
    price: 35.99,
    image: '/images/premier-league/arsenal/2/1.jpg',
    images: [
      '/images/premier-league/arsenal/2/1.jpg',
      '/images/premier-league/arsenal/2/2.jpg',
      '/images/premier-league/arsenal/2/3.jpg',
      '/images/premier-league/arsenal/2/4.jpg',
      '/images/premier-league/arsenal/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Premier League - Chelsea FC
  {
    id: 'chelsea-1',
    team: 'Chelsea FC',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/chelsea/1/1.jpg',
    images: [
      '/images/premier-league/chelsea/1/1.jpg',
      '/images/premier-league/chelsea/1/2.jpg',
      '/images/premier-league/chelsea/1/3.jpg',
      '/images/premier-league/chelsea/1/4.jpg',
      '/images/premier-league/chelsea/1/5.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },
  {
    id: 'chelsea-2',
    team: 'Chelsea FC',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/chelsea/2/1.jpg',
    images: [
      '/images/premier-league/chelsea/2/1.jpg',
      '/images/premier-league/chelsea/2/2.jpg',
      '/images/premier-league/chelsea/2/3.jpg',
      '/images/premier-league/chelsea/2/4.jpg',
      '/images/premier-league/chelsea/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Serie A - Inter Milan
  {
    id: 'inter-milan-1',
    team: 'Inter Milan',
    league: 'serie-a',
    price: 35.99,
    image: '/images/serie-a/inter-milan/1/1.jpg',
    images: [
      '/images/serie-a/inter-milan/1/1.jpg',
      '/images/serie-a/inter-milan/1/2.jpg',
      '/images/serie-a/inter-milan/1/3.jpg',
      '/images/serie-a/inter-milan/1/4.jpg',
      '/images/serie-a/inter-milan/1/5.jpg',
    ],
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'inter-milan-2',
    team: 'Inter Milan',
    league: 'serie-a',
    price: 35.99,
    image: '/images/serie-a/inter-milan/2/1.jpg',
    images: [
      '/images/serie-a/inter-milan/2/1.jpg',
      '/images/serie-a/inter-milan/2/2.jpg',
      '/images/serie-a/inter-milan/2/3.jpg',
      '/images/serie-a/inter-milan/2/4.jpg',
      '/images/serie-a/inter-milan/2/5.jpg',
      '/images/serie-a/inter-milan/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Serie A - AC Milan
  {
    id: 'ac-milan-1',
    team: 'AC Milan',
    league: 'serie-a',
    price: 35.99,
    image: '/images/serie-a/ac-milan/1/1.jpg',
    images: [
      '/images/serie-a/ac-milan/1/1.jpg',
      '/images/serie-a/ac-milan/1/2.jpg',
      '/images/serie-a/ac-milan/1/3.jpg',
      '/images/serie-a/ac-milan/1/4.jpg',
      '/images/serie-a/ac-milan/1/5.jpg',
      '/images/serie-a/ac-milan/1/6.jpg',
      '/images/serie-a/ac-milan/1/7.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'ac-milan-2',
    team: 'AC Milan',
    league: 'serie-a',
    price: 35.99,
    image: '/images/serie-a/ac-milan/2/1.jpg',
    images: [
      '/images/serie-a/ac-milan/2/1.jpg',
      '/images/serie-a/ac-milan/2/2.jpg',
      '/images/serie-a/ac-milan/2/3.jpg',
      '/images/serie-a/ac-milan/2/4.jpg',
      '/images/serie-a/ac-milan/2/5.jpg',
      '/images/serie-a/ac-milan/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Serie A - Juventus FC
  {
    id: 'juventus-1',
    team: 'Juventus FC',
    league: 'serie-a',
    price: 32.99,
    originalPrice: 99.99,
    image: '/images/serie-a/juventus/1/1.jpg',
    images: [
      '/images/serie-a/juventus/1/1.jpg',
      '/images/serie-a/juventus/1/2.jpg',
      '/images/serie-a/juventus/1/3.jpg',
      '/images/serie-a/juventus/1/4.jpg',
      '/images/serie-a/juventus/1/5.jpg',
      '/images/serie-a/juventus/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Serie A - SSC Napoli
  {
    id: 'napoli-1',
    team: 'SSC Napoli',
    league: 'serie-a',
    price: 32.99,
    image: '/images/serie-a/napoli/1/1.jpg',
    images: [
      '/images/serie-a/napoli/1/1.jpg',
      '/images/serie-a/napoli/1/2.jpg',
      '/images/serie-a/napoli/1/3.jpg',
      '/images/serie-a/napoli/1/4.jpg',
      '/images/serie-a/napoli/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'napoli-2',
    team: 'SSC Napoli',
    league: 'serie-a',
    price: 32.99,
    image: '/images/serie-a/napoli/2/1.jpg',
    images: [
      '/images/serie-a/napoli/2/1.jpg',
      '/images/serie-a/napoli/2/2.jpg',
      '/images/serie-a/napoli/2/3.jpg',
      '/images/serie-a/napoli/2/4.jpg',
      '/images/serie-a/napoli/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Bundesliga - Bayern München
  {
    id: 'bayern-munich-1',
    team: 'Bayern München',
    league: 'bundesliga',
    price: 35.99,
    image: '/images/bundesliga/bayern-munich/1/1.jpg',
    images: [
      '/images/bundesliga/bayern-munich/1/1.jpg',
      '/images/bundesliga/bayern-munich/1/2.jpg',
      '/images/bundesliga/bayern-munich/1/3.jpg',
      '/images/bundesliga/bayern-munich/1/4.jpg',
      '/images/bundesliga/bayern-munich/1/5.jpg',
      '/images/bundesliga/bayern-munich/1/6.jpg',
    ],
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'bayern-munich-2',
    team: 'Bayern München',
    league: 'bundesliga',
    price: 35.99,
    image: '/images/bundesliga/bayern-munich/2/1.jpg',
    images: [
      '/images/bundesliga/bayern-munich/2/1.jpg',
      '/images/bundesliga/bayern-munich/2/2.jpg',
      '/images/bundesliga/bayern-munich/2/3.jpg',
      '/images/bundesliga/bayern-munich/2/4.jpg',
      '/images/bundesliga/bayern-munich/2/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'bayern-munich-3',
    team: 'Bayern München',
    league: 'bundesliga',
    price: 35.99,
    image: '/images/bundesliga/bayern-munich/3/1.jpg',
    images: [
      '/images/bundesliga/bayern-munich/3/1.jpg',
      '/images/bundesliga/bayern-munich/3/2.jpg',
      '/images/bundesliga/bayern-munich/3/3.jpg',
      '/images/bundesliga/bayern-munich/3/4.jpg',
      '/images/bundesliga/bayern-munich/3/5.jpg',
    ],
    season: '2024/25',
  },

  // Bundesliga - Borussia Dortmund
  {
    id: 'dortmund-1',
    team: 'Borussia Dortmund',
    league: 'bundesliga',
    price: 35.99,
    image: '/images/bundesliga/dortmund/1/1.jpg',
    images: [
      '/images/bundesliga/dortmund/1/1.jpg',
      '/images/bundesliga/dortmund/1/2.jpg',
      '/images/bundesliga/dortmund/1/3.jpg',
      '/images/bundesliga/dortmund/1/4.jpg',
      '/images/bundesliga/dortmund/1/5.jpg',
      '/images/bundesliga/dortmund/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'dortmund-2',
    team: 'Borussia Dortmund',
    league: 'bundesliga',
    price: 35.99,
    image: '/images/bundesliga/dortmund/2/1.jpg',
    images: [
      '/images/bundesliga/dortmund/2/1.jpg',
      '/images/bundesliga/dortmund/2/2.jpg',
      '/images/bundesliga/dortmund/2/3.jpg',
      '/images/bundesliga/dortmund/2/4.jpg',
      '/images/bundesliga/dortmund/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Bundesliga - Bayer Leverkusen
  {
    id: 'leverkusen-1',
    team: 'Bayer Leverkusen',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/leverkusen/1/1.jpg',
    images: [
      '/images/bundesliga/leverkusen/1/1.jpg',
      '/images/bundesliga/leverkusen/1/2.jpg',
      '/images/bundesliga/leverkusen/1/3.jpg',
      '/images/bundesliga/leverkusen/1/4.jpg',
      '/images/bundesliga/leverkusen/1/5.jpg',
      '/images/bundesliga/leverkusen/1/6.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },
  {
    id: 'leverkusen-2',
    team: 'Bayer Leverkusen',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/leverkusen/2/1.jpg',
    images: [
      '/images/bundesliga/leverkusen/2/1.jpg',
      '/images/bundesliga/leverkusen/2/2.jpg',
      '/images/bundesliga/leverkusen/2/3.jpg',
      '/images/bundesliga/leverkusen/2/4.jpg',
      '/images/bundesliga/leverkusen/2/5.jpg',
      '/images/bundesliga/leverkusen/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Ligue 1 - Paris Saint-Germain
  {
    id: 'psg-1',
    team: 'Paris Saint-Germain',
    league: 'ligue-1',
    price: 35.99,
    image: '/images/ligue-1/psg/1/1.jpg',
    images: [
      '/images/ligue-1/psg/1/1.jpg',
      '/images/ligue-1/psg/1/2.jpg',
      '/images/ligue-1/psg/1/3.jpg',
      '/images/ligue-1/psg/1/4.jpg',
      '/images/ligue-1/psg/1/5.jpg',
      '/images/ligue-1/psg/1/6.jpg',
    ],
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'psg-2',
    team: 'Paris Saint-Germain',
    league: 'ligue-1',
    price: 35.99,
    image: '/images/ligue-1/psg/2/1.jpg',
    images: [
      '/images/ligue-1/psg/2/1.jpg',
      '/images/ligue-1/psg/2/2.jpg',
      '/images/ligue-1/psg/2/3.jpg',
      '/images/ligue-1/psg/2/4.jpg',
      '/images/ligue-1/psg/2/5.jpg',
      '/images/ligue-1/psg/2/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'psg-3',
    team: 'Paris Saint-Germain',
    league: 'ligue-1',
    price: 35.99,
    image: '/images/ligue-1/psg/3/1.jpg',
    images: [
      '/images/ligue-1/psg/3/1.jpg',
      '/images/ligue-1/psg/3/2.jpg',
      '/images/ligue-1/psg/3/3.jpg',
      '/images/ligue-1/psg/3/4.jpg',
      '/images/ligue-1/psg/3/5.jpg',
      '/images/ligue-1/psg/3/6.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },
  {
    id: 'psg-4',
    team: 'Paris Saint-Germain',
    league: 'ligue-1',
    price: 35.99,
    image: '/images/ligue-1/psg/4/1.jpg',
    images: [
      '/images/ligue-1/psg/4/1.jpg',
      '/images/ligue-1/psg/4/2.jpg',
      '/images/ligue-1/psg/4/3.jpg',
      '/images/ligue-1/psg/4/4.jpg',
      '/images/ligue-1/psg/4/5.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },

  // Ligue 1 - Olympique de Marseille
  {
    id: 'marseille-1',
    team: 'Olympique de Marseille',
    league: 'ligue-1',
    price: 32.99,
    image: '/images/ligue-1/marseille/1/1.jpg',
    images: [
      '/images/ligue-1/marseille/1/1.jpg',
      '/images/ligue-1/marseille/1/2.jpg',
      '/images/ligue-1/marseille/1/3.jpg',
      '/images/ligue-1/marseille/1/4.jpg',
      '/images/ligue-1/marseille/1/5.jpg',
      '/images/ligue-1/marseille/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'marseille-2',
    team: 'Olympique de Marseille',
    league: 'ligue-1',
    price: 32.99,
    image: '/images/ligue-1/marseille/2/1.jpg',
    images: [
      '/images/ligue-1/marseille/2/1.jpg',
      '/images/ligue-1/marseille/2/2.jpg',
      '/images/ligue-1/marseille/2/3.jpg',
      '/images/ligue-1/marseille/2/4.jpg',
      '/images/ligue-1/marseille/2/5.jpg',
      '/images/ligue-1/marseille/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Brasileirão - Flamengo
  {
    id: 'flamengo-1',
    team: 'Flamengo',
    league: 'brasileirao',
    price: 35.99,
    image: '/images/brasileirao/flamengo/1/1.jpg',
    images: [
      '/images/brasileirao/flamengo/1/1.jpg',
      '/images/brasileirao/flamengo/1/2.jpg',
      '/images/brasileirao/flamengo/1/3.jpg',
      '/images/brasileirao/flamengo/1/4.jpg',
      '/images/brasileirao/flamengo/1/5.jpg',
    ],
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'flamengo-2',
    team: 'Flamengo',
    league: 'brasileirao',
    price: 35.99,
    image: '/images/brasileirao/flamengo/2/1.jpg',
    images: [
      '/images/brasileirao/flamengo/2/1.jpg',
      '/images/brasileirao/flamengo/2/2.jpg',
      '/images/brasileirao/flamengo/2/3.jpg',
      '/images/brasileirao/flamengo/2/4.jpg',
      '/images/brasileirao/flamengo/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Brasileirão - Palmeiras
  {
    id: 'palmeiras-1',
    team: 'Palmeiras',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/palmeiras/1/1.jpg',
    images: [
      '/images/brasileirao/palmeiras/1/1.jpg',
      '/images/brasileirao/palmeiras/1/2.jpg',
      '/images/brasileirao/palmeiras/1/3.jpg',
      '/images/brasileirao/palmeiras/1/4.jpg',
      '/images/brasileirao/palmeiras/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'palmeiras-2',
    team: 'Palmeiras',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/palmeiras/2/1.jpg',
    images: [
      '/images/brasileirao/palmeiras/2/1.jpg',
      '/images/brasileirao/palmeiras/2/2.jpg',
      '/images/brasileirao/palmeiras/2/3.jpg',
      '/images/brasileirao/palmeiras/2/4.jpg',
      '/images/brasileirao/palmeiras/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Brasileirão - Santos
  {
    id: 'santos-1',
    team: 'Santos',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/santos/1/1.jpg',
    images: [
      '/images/brasileirao/santos/1/1.jpg',
      '/images/brasileirao/santos/1/2.jpg',
      '/images/brasileirao/santos/1/3.jpg',
      '/images/brasileirao/santos/1/4.jpg',
      '/images/brasileirao/santos/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'santos-2',
    team: 'Santos',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/santos/2/1.jpg',
    images: [
      '/images/brasileirao/santos/2/1.jpg',
      '/images/brasileirao/santos/2/2.jpg',
      '/images/brasileirao/santos/2/3.jpg',
      '/images/brasileirao/santos/2/4.jpg',
      '/images/brasileirao/santos/2/5.jpg',
      '/images/brasileirao/santos/2/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'santos-3',
    team: 'Santos',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/santos/3/1.jpg',
    images: [
      '/images/brasileirao/santos/3/1.jpg',
      '/images/brasileirao/santos/3/2.jpg',
      '/images/brasileirao/santos/3/3.jpg',
      '/images/brasileirao/santos/3/4.jpg',
      '/images/brasileirao/santos/3/5.jpg',
      '/images/brasileirao/santos/3/6.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },

  // Resto de Ligas - Boca Juniors
  {
    id: 'boca-juniors-1',
    team: 'Boca Juniors',
    league: 'resto-de-ligas',
    price: 35.99,
    image: '/images/resto-de-ligas/boca-juniors/1/1.jpg',
    images: [
      '/images/resto-de-ligas/boca-juniors/1/1.jpg',
      '/images/resto-de-ligas/boca-juniors/1/2.jpg',
      '/images/resto-de-ligas/boca-juniors/1/3.jpg',
      '/images/resto-de-ligas/boca-juniors/1/4.jpg',
      '/images/resto-de-ligas/boca-juniors/1/5.jpg',
      '/images/resto-de-ligas/boca-juniors/1/6.jpg',
    ],
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'boca-juniors-2',
    team: 'Boca Juniors',
    league: 'resto-de-ligas',
    price: 35.99,
    image: '/images/resto-de-ligas/boca-juniors/2/1.jpg',
    images: [
      '/images/resto-de-ligas/boca-juniors/2/1.jpg',
      '/images/resto-de-ligas/boca-juniors/2/2.jpg',
      '/images/resto-de-ligas/boca-juniors/2/3.jpg',
      '/images/resto-de-ligas/boca-juniors/2/4.jpg',
      '/images/resto-de-ligas/boca-juniors/2/5.jpg',
      '/images/resto-de-ligas/boca-juniors/2/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'boca-juniors-3',
    team: 'Boca Juniors',
    league: 'resto-de-ligas',
    price: 35.99,
    image: '/images/resto-de-ligas/boca-juniors/3/1.jpg',
    images: [
      '/images/resto-de-ligas/boca-juniors/3/1.jpg',
      '/images/resto-de-ligas/boca-juniors/3/2.jpg',
      '/images/resto-de-ligas/boca-juniors/3/3.jpg',
      '/images/resto-de-ligas/boca-juniors/3/4.jpg',
      '/images/resto-de-ligas/boca-juniors/3/5.jpg',
    ],
    season: '2024/25',
  },

  // Resto de Ligas - River Plate
  {
    id: 'river-plate-1',
    team: 'River Plate',
    league: 'resto-de-ligas',
    price: 35.99,
    image: '/images/resto-de-ligas/river-plate/1/1.jpg',
    images: [
      '/images/resto-de-ligas/river-plate/1/1.jpg',
      '/images/resto-de-ligas/river-plate/1/2.jpg',
      '/images/resto-de-ligas/river-plate/1/3.jpg',
      '/images/resto-de-ligas/river-plate/1/4.jpg',
      '/images/resto-de-ligas/river-plate/1/5.jpg',
      '/images/resto-de-ligas/river-plate/1/6.jpg',
    ],
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'river-plate-2',
    team: 'River Plate',
    league: 'resto-de-ligas',
    price: 35.99,
    image: '/images/resto-de-ligas/river-plate/2/1.jpg',
    images: [
      '/images/resto-de-ligas/river-plate/2/1.jpg',
      '/images/resto-de-ligas/river-plate/2/2.jpg',
      '/images/resto-de-ligas/river-plate/2/3.jpg',
      '/images/resto-de-ligas/river-plate/2/4.jpg',
      '/images/resto-de-ligas/river-plate/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Resto de Ligas - Independiente
  {
    id: 'independiente-1',
    team: 'Independiente',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/independiente/1/1.jpg',
    images: [
      '/images/resto-de-ligas/independiente/1/1.jpg',
      '/images/resto-de-ligas/independiente/1/2.jpg',
      '/images/resto-de-ligas/independiente/1/3.jpg',
      '/images/resto-de-ligas/independiente/1/4.jpg',
      '/images/resto-de-ligas/independiente/1/5.jpg',
      '/images/resto-de-ligas/independiente/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Resto de Ligas - Ajax
  {
    id: 'ajax-1',
    team: 'Ajax',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/ajax/1/1.jpg',
    images: [
      '/images/resto-de-ligas/ajax/1/1.jpg',
      '/images/resto-de-ligas/ajax/1/2.jpg',
      '/images/resto-de-ligas/ajax/1/3.jpg',
      '/images/resto-de-ligas/ajax/1/4.jpg',
      '/images/resto-de-ligas/ajax/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Resto de Ligas - Benfica
  {
    id: 'benfica-1',
    team: 'Benfica',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/benfica/1/1.jpg',
    images: [
      '/images/resto-de-ligas/benfica/1/1.jpg',
      '/images/resto-de-ligas/benfica/1/2.jpg',
      '/images/resto-de-ligas/benfica/1/3.jpg',
      '/images/resto-de-ligas/benfica/1/4.jpg',
      '/images/resto-de-ligas/benfica/1/5.jpg',
      '/images/resto-de-ligas/benfica/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Resto de Ligas - Galatasaray
  {
    id: 'galatasaray-1',
    team: 'Galatasaray',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/galatasaray/1/1.jpg',
    images: [
      '/images/resto-de-ligas/galatasaray/1/1.jpg',
      '/images/resto-de-ligas/galatasaray/1/2.jpg',
      '/images/resto-de-ligas/galatasaray/1/3.jpg',
      '/images/resto-de-ligas/galatasaray/1/4.jpg',
      '/images/resto-de-ligas/galatasaray/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Resto de Ligas - Inter Miami
  {
    id: 'inter-miami-1',
    team: 'Inter Miami',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/inter-miami/1/1.jpg',
    images: [
      '/images/resto-de-ligas/inter-miami/1/1.jpg',
      '/images/resto-de-ligas/inter-miami/1/2.jpg',
      '/images/resto-de-ligas/inter-miami/1/3.jpg',
      '/images/resto-de-ligas/inter-miami/1/4.jpg',
      '/images/resto-de-ligas/inter-miami/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'inter-miami-2',
    team: 'Inter Miami',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/inter-miami/2/1.jpg',
    images: [
      '/images/resto-de-ligas/inter-miami/2/1.jpg',
      '/images/resto-de-ligas/inter-miami/2/2.jpg',
      '/images/resto-de-ligas/inter-miami/2/3.jpg',
      '/images/resto-de-ligas/inter-miami/2/4.jpg',
      '/images/resto-de-ligas/inter-miami/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Resto de Ligas - LA Galaxy
  {
    id: 'la-galaxy-1',
    team: 'LA Galaxy',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/la-galaxy/1/1.jpg',
    images: [
      '/images/resto-de-ligas/la-galaxy/1/1.jpg',
      '/images/resto-de-ligas/la-galaxy/1/2.jpg',
      '/images/resto-de-ligas/la-galaxy/1/3.jpg',
      '/images/resto-de-ligas/la-galaxy/1/4.jpg',
      '/images/resto-de-ligas/la-galaxy/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'la-galaxy-2',
    team: 'LA Galaxy',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/la-galaxy/2/1.jpg',
    images: [
      '/images/resto-de-ligas/la-galaxy/2/1.jpg',
      '/images/resto-de-ligas/la-galaxy/2/2.jpg',
      '/images/resto-de-ligas/la-galaxy/2/3.jpg',
      '/images/resto-de-ligas/la-galaxy/2/4.jpg',
      '/images/resto-de-ligas/la-galaxy/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Resto de Ligas - América de Cali
  {
    id: 'america-cali-1',
    team: 'América de Cali',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/america-cali/1/1.jpg',
    images: [
      '/images/resto-de-ligas/america-cali/1/1.jpg',
      '/images/resto-de-ligas/america-cali/1/2.jpg',
      '/images/resto-de-ligas/america-cali/1/3.jpg',
      '/images/resto-de-ligas/america-cali/1/4.jpg',
      '/images/resto-de-ligas/america-cali/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Resto de Ligas - Colo Colo
  {
    id: 'colo-colo-1',
    team: 'Colo Colo',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/colo-colo/1/1.jpg',
    images: [
      '/images/resto-de-ligas/colo-colo/1/1.jpg',
      '/images/resto-de-ligas/colo-colo/1/2.jpg',
      '/images/resto-de-ligas/colo-colo/1/3.jpg',
      '/images/resto-de-ligas/colo-colo/1/4.jpg',
      '/images/resto-de-ligas/colo-colo/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Resto de Ligas - Nacional
  {
    id: 'nacional-1',
    team: 'Nacional',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/nacional/1/1.jpg',
    images: [
      '/images/resto-de-ligas/nacional/1/1.jpg',
      '/images/resto-de-ligas/nacional/1/2.jpg',
      '/images/resto-de-ligas/nacional/1/3.jpg',
      '/images/resto-de-ligas/nacional/1/4.jpg',
      '/images/resto-de-ligas/nacional/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Resto de Ligas - Universidad de Chile
  {
    id: 'universidad-chile-1',
    team: 'Universidad de Chile',
    league: 'resto-de-ligas',
    price: 32.99,
    image: '/images/resto-de-ligas/universidad-chile/1/1.jpg',
    images: [
      '/images/resto-de-ligas/universidad-chile/1/1.jpg',
      '/images/resto-de-ligas/universidad-chile/1/2.jpg',
      '/images/resto-de-ligas/universidad-chile/1/3.jpg',
      '/images/resto-de-ligas/universidad-chile/1/4.jpg',
      '/images/resto-de-ligas/universidad-chile/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Argentina
  {
    id: 'argentina-1',
    team: 'Argentina',
    league: 'selecciones',
    price: 35.99,
    image: '/images/selecciones/argentina/1/1.jpg',
    images: [
      '/images/selecciones/argentina/1/1.jpg',
      '/images/selecciones/argentina/1/2.jpg',
      '/images/selecciones/argentina/1/3.jpg',
      '/images/selecciones/argentina/1/4.jpg',
      '/images/selecciones/argentina/1/5.jpg',
      '/images/selecciones/argentina/1/6.jpg',
      '/images/selecciones/argentina/1/7.jpg',
    ],
    season: '2024/25',
    isBestseller: true,
  },

  // Selecciones - Brasil
  {
    id: 'brasil-1',
    team: 'Brasil',
    league: 'selecciones',
    price: 35.99,
    image: '/images/selecciones/brasil/1/1.jpg',
    images: [
      '/images/selecciones/brasil/1/1.jpg',
      '/images/selecciones/brasil/1/2.jpg',
      '/images/selecciones/brasil/1/3.jpg',
      '/images/selecciones/brasil/1/4.jpg',
      '/images/selecciones/brasil/1/5.jpg',
      '/images/selecciones/brasil/1/6.jpg',
    ],
    season: '2024/25',
    isBestseller: true,
  },

  // Selecciones - España
  {
    id: 'espana-1',
    team: 'España',
    league: 'selecciones',
    price: 35.99,
    image: '/images/selecciones/espana/1/1.jpg',
    images: [
      '/images/selecciones/espana/1/1.jpg',
      '/images/selecciones/espana/1/2.jpg',
      '/images/selecciones/espana/1/3.jpg',
      '/images/selecciones/espana/1/4.jpg',
      '/images/selecciones/espana/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Francia
  {
    id: 'francia-1',
    team: 'Francia',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/francia/1/1.jpg',
    images: [
      '/images/selecciones/francia/1/1.jpg',
      '/images/selecciones/francia/1/2.jpg',
      '/images/selecciones/francia/1/3.jpg',
      '/images/selecciones/francia/1/4.jpg',
      '/images/selecciones/francia/1/5.jpg',
      '/images/selecciones/francia/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Alemania
  {
    id: 'alemania-1',
    team: 'Alemania',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/alemania/1/1.jpg',
    images: [
      '/images/selecciones/alemania/1/1.jpg',
      '/images/selecciones/alemania/1/2.jpg',
      '/images/selecciones/alemania/1/3.jpg',
      '/images/selecciones/alemania/1/4.jpg',
      '/images/selecciones/alemania/1/5.jpg',
      '/images/selecciones/alemania/1/6.jpg',
      '/images/selecciones/alemania/1/7.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },

  // Selecciones - Italia
  {
    id: 'italia-1',
    team: 'Italia',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/italia/1/1.jpg',
    images: [
      '/images/selecciones/italia/1/1.jpg',
      '/images/selecciones/italia/1/2.jpg',
      '/images/selecciones/italia/1/3.jpg',
      '/images/selecciones/italia/1/4.jpg',
      '/images/selecciones/italia/1/5.jpg',
      '/images/selecciones/italia/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Inglaterra
  {
    id: 'inglaterra-1',
    team: 'Inglaterra',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/inglaterra/1/1.jpg',
    images: [
      '/images/selecciones/inglaterra/1/1.jpg',
      '/images/selecciones/inglaterra/1/2.jpg',
      '/images/selecciones/inglaterra/1/3.jpg',
      '/images/selecciones/inglaterra/1/4.jpg',
      '/images/selecciones/inglaterra/1/5.jpg',
      '/images/selecciones/inglaterra/1/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Valencia
  {
    id: 'valencia-1',
    team: 'Valencia',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/valencia/1/1.jpg',
    images: [
      '/images/la-liga/valencia/1/1.jpg',
      '/images/la-liga/valencia/1/2.jpg',
      '/images/la-liga/valencia/1/3.jpg',
      '/images/la-liga/valencia/1/4.jpg',
      '/images/la-liga/valencia/1/5.jpg',
      '/images/la-liga/valencia/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'valencia-2',
    team: 'Valencia',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/valencia/2/1.jpg',
    images: [
      '/images/la-liga/valencia/2/1.jpg',
      '/images/la-liga/valencia/2/2.jpg',
      '/images/la-liga/valencia/2/3.jpg',
      '/images/la-liga/valencia/2/4.jpg',
      '/images/la-liga/valencia/2/5.jpg',
      '/images/la-liga/valencia/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Oviedo
  {
    id: 'oviedo-1',
    team: 'Oviedo',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/oviedo/1/1.jpg',
    images: [
      '/images/la-liga/oviedo/1/1.jpg',
      '/images/la-liga/oviedo/1/2.jpg',
      '/images/la-liga/oviedo/1/3.jpg',
      '/images/la-liga/oviedo/1/4.jpg',
      '/images/la-liga/oviedo/1/5.jpg',
      '/images/la-liga/oviedo/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'oviedo-2',
    team: 'Oviedo',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/oviedo/2/1.jpg',
    images: [
      '/images/la-liga/oviedo/2/1.jpg',
      '/images/la-liga/oviedo/2/2.jpg',
      '/images/la-liga/oviedo/2/3.jpg',
      '/images/la-liga/oviedo/2/4.jpg',
      '/images/la-liga/oviedo/2/5.jpg',
      '/images/la-liga/oviedo/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Real Betis
  {
    id: 'real-betis-1',
    team: 'Real Betis',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/real-betis/1/1.jpg',
    images: [
      '/images/la-liga/real-betis/1/1.jpg',
      '/images/la-liga/real-betis/1/2.jpg',
      '/images/la-liga/real-betis/1/3.jpg',
      '/images/la-liga/real-betis/1/4.jpg',
      '/images/la-liga/real-betis/1/5.jpg',
      '/images/la-liga/real-betis/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'real-betis-2',
    team: 'Real Betis',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/real-betis/2/1.jpg',
    images: [
      '/images/la-liga/real-betis/2/1.jpg',
      '/images/la-liga/real-betis/2/2.jpg',
      '/images/la-liga/real-betis/2/3.jpg',
      '/images/la-liga/real-betis/2/4.jpg',
      '/images/la-liga/real-betis/2/5.jpg',
      '/images/la-liga/real-betis/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Tenerife
  {
    id: 'tenerife-1',
    team: 'Tenerife',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/tenerife/1/1.jpg',
    images: [
      '/images/la-liga/tenerife/1/1.jpg',
      '/images/la-liga/tenerife/1/2.jpg',
      '/images/la-liga/tenerife/1/3.jpg',
      '/images/la-liga/tenerife/1/4.jpg',
      '/images/la-liga/tenerife/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'tenerife-2',
    team: 'Tenerife',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/tenerife/2/1.jpg',
    images: [
      '/images/la-liga/tenerife/2/1.jpg',
      '/images/la-liga/tenerife/2/2.jpg',
      '/images/la-liga/tenerife/2/3.jpg',
      '/images/la-liga/tenerife/2/4.jpg',
      '/images/la-liga/tenerife/2/5.jpg',
      '/images/la-liga/tenerife/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Sevilla
  {
    id: 'sevilla-1',
    team: 'Sevilla',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/sevilla/1/1.jpg',
    images: [
      '/images/la-liga/sevilla/1/1.jpg',
      '/images/la-liga/sevilla/1/2.jpg',
      '/images/la-liga/sevilla/1/3.jpg',
      '/images/la-liga/sevilla/1/4.jpg',
      '/images/la-liga/sevilla/1/5.jpg',
      '/images/la-liga/sevilla/1/6.jpg',
      '/images/la-liga/sevilla/1/7.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'sevilla-2',
    team: 'Sevilla',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/sevilla/2/1.jpg',
    images: [
      '/images/la-liga/sevilla/2/1.jpg',
      '/images/la-liga/sevilla/2/2.jpg',
      '/images/la-liga/sevilla/2/3.jpg',
      '/images/la-liga/sevilla/2/4.jpg',
      '/images/la-liga/sevilla/2/5.jpg',
      '/images/la-liga/sevilla/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - RCD Mallorca
  {
    id: 'rcd-mallorca-1',
    team: 'RCD Mallorca',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/rcd-mallorca/1/1.jpg',
    images: [
      '/images/la-liga/rcd-mallorca/1/1.jpg',
      '/images/la-liga/rcd-mallorca/1/2.jpg',
      '/images/la-liga/rcd-mallorca/1/3.jpg',
      '/images/la-liga/rcd-mallorca/1/4.jpg',
      '/images/la-liga/rcd-mallorca/1/5.jpg',
      '/images/la-liga/rcd-mallorca/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'rcd-mallorca-2',
    team: 'RCD Mallorca',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/rcd-mallorca/2/1.jpg',
    images: [
      '/images/la-liga/rcd-mallorca/2/1.jpg',
      '/images/la-liga/rcd-mallorca/2/2.jpg',
      '/images/la-liga/rcd-mallorca/2/3.jpg',
      '/images/la-liga/rcd-mallorca/2/4.jpg',
      '/images/la-liga/rcd-mallorca/2/5.jpg',
      '/images/la-liga/rcd-mallorca/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Málaga
  {
    id: 'malaga-1',
    team: 'Málaga',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/malaga/1/1.jpg',
    images: [
      '/images/la-liga/malaga/1/1.jpg',
      '/images/la-liga/malaga/1/2.jpg',
      '/images/la-liga/malaga/1/3.jpg',
      '/images/la-liga/malaga/1/4.jpg',
      '/images/la-liga/malaga/1/5.jpg',
      '/images/la-liga/malaga/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'malaga-2',
    team: 'Málaga',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/malaga/2/1.jpg',
    images: [
      '/images/la-liga/malaga/2/1.jpg',
      '/images/la-liga/malaga/2/2.jpg',
      '/images/la-liga/malaga/2/3.jpg',
      '/images/la-liga/malaga/2/4.jpg',
      '/images/la-liga/malaga/2/5.jpg',
      '/images/la-liga/malaga/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Girona
  {
    id: 'girona-1',
    team: 'Girona',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/girona/1/1.jpg',
    images: [
      '/images/la-liga/girona/1/1.jpg',
      '/images/la-liga/girona/1/2.jpg',
      '/images/la-liga/girona/1/3.jpg',
      '/images/la-liga/girona/1/4.jpg',
      '/images/la-liga/girona/1/5.jpg',
      '/images/la-liga/girona/1/6.jpg',
      '/images/la-liga/girona/1/7.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'girona-2',
    team: 'Girona',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/girona/2/1.jpg',
    images: [
      '/images/la-liga/girona/2/1.jpg',
      '/images/la-liga/girona/2/2.jpg',
      '/images/la-liga/girona/2/3.jpg',
      '/images/la-liga/girona/2/4.jpg',
      '/images/la-liga/girona/2/5.jpg',
      '/images/la-liga/girona/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Deportivo la Coruña
  {
    id: 'deportivo-la-coruna-1',
    team: 'Deportivo la Coruña',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/deportivo-la-coruna/1/1.jpg',
    images: [
      '/images/la-liga/deportivo-la-coruna/1/1.jpg',
      '/images/la-liga/deportivo-la-coruna/1/2.jpg',
      '/images/la-liga/deportivo-la-coruna/1/3.jpg',
      '/images/la-liga/deportivo-la-coruna/1/4.jpg',
      '/images/la-liga/deportivo-la-coruna/1/5.jpg',
      '/images/la-liga/deportivo-la-coruna/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'deportivo-la-coruna-2',
    team: 'Deportivo la Coruña',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/deportivo-la-coruna/2/1.jpg',
    images: [
      '/images/la-liga/deportivo-la-coruna/2/1.jpg',
      '/images/la-liga/deportivo-la-coruna/2/2.jpg',
      '/images/la-liga/deportivo-la-coruna/2/3.jpg',
      '/images/la-liga/deportivo-la-coruna/2/4.jpg',
      '/images/la-liga/deportivo-la-coruna/2/5.jpg',
      '/images/la-liga/deportivo-la-coruna/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Córdoba
  {
    id: 'cordoba-1',
    team: 'Córdoba',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/cordoba/1/1.jpg',
    images: [
      '/images/la-liga/cordoba/1/1.jpg',
      '/images/la-liga/cordoba/1/2.jpg',
      '/images/la-liga/cordoba/1/3.jpg',
      '/images/la-liga/cordoba/1/4.jpg',
      '/images/la-liga/cordoba/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'cordoba-2',
    team: 'Córdoba',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/cordoba/2/1.jpg',
    images: [
      '/images/la-liga/cordoba/2/1.jpg',
      '/images/la-liga/cordoba/2/2.jpg',
      '/images/la-liga/cordoba/2/3.jpg',
      '/images/la-liga/cordoba/2/4.jpg',
      '/images/la-liga/cordoba/2/5.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Celta
  {
    id: 'celta-1',
    team: 'Celta',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/celta/1/1.jpg',
    images: [
      '/images/la-liga/celta/1/1.jpg',
      '/images/la-liga/celta/1/2.jpg',
      '/images/la-liga/celta/1/3.jpg',
      '/images/la-liga/celta/1/4.jpg',
      '/images/la-liga/celta/1/5.jpg',
      '/images/la-liga/celta/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'celta-2',
    team: 'Celta',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/celta/2/1.jpg',
    images: [
      '/images/la-liga/celta/2/1.jpg',
      '/images/la-liga/celta/2/2.jpg',
      '/images/la-liga/celta/2/3.jpg',
      '/images/la-liga/celta/2/4.jpg',
      '/images/la-liga/celta/2/5.jpg',
      '/images/la-liga/celta/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Cádiz
  {
    id: 'cadiz-1',
    team: 'Cádiz',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/cadiz/1/1.jpg',
    images: [
      '/images/la-liga/cadiz/1/1.jpg',
      '/images/la-liga/cadiz/1/2.jpg',
      '/images/la-liga/cadiz/1/3.jpg',
      '/images/la-liga/cadiz/1/4.jpg',
      '/images/la-liga/cadiz/1/5.jpg',
      '/images/la-liga/cadiz/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'cadiz-2',
    team: 'Cádiz',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/cadiz/2/1.jpg',
    images: [
      '/images/la-liga/cadiz/2/1.jpg',
      '/images/la-liga/cadiz/2/2.jpg',
      '/images/la-liga/cadiz/2/3.jpg',
      '/images/la-liga/cadiz/2/4.jpg',
      '/images/la-liga/cadiz/2/5.jpg',
      '/images/la-liga/cadiz/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Athletic Bilbao
  {
    id: 'athletic-bilbao-1',
    team: 'Athletic Bilbao',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/athletic-bilbao/1/1.jpg',
    images: [
      '/images/la-liga/athletic-bilbao/1/1.jpg',
      '/images/la-liga/athletic-bilbao/1/2.jpg',
      '/images/la-liga/athletic-bilbao/1/3.jpg',
      '/images/la-liga/athletic-bilbao/1/4.jpg',
      '/images/la-liga/athletic-bilbao/1/5.jpg',
      '/images/la-liga/athletic-bilbao/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'athletic-bilbao-2',
    team: 'Athletic Bilbao',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/athletic-bilbao/2/1.jpg',
    images: [
      '/images/la-liga/athletic-bilbao/2/1.jpg',
      '/images/la-liga/athletic-bilbao/2/2.jpg',
      '/images/la-liga/athletic-bilbao/2/3.jpg',
      '/images/la-liga/athletic-bilbao/2/4.jpg',
      '/images/la-liga/athletic-bilbao/2/5.jpg',
      '/images/la-liga/athletic-bilbao/2/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Zaragoza
  {
    id: 'zaragoza-1',
    team: 'Zaragoza',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/zaragoza/1/1.jpg',
    images: [
      '/images/la-liga/zaragoza/1/1.jpg',
      '/images/la-liga/zaragoza/1/2.jpg',
      '/images/la-liga/zaragoza/1/3.jpg',
      '/images/la-liga/zaragoza/1/4.jpg',
      '/images/la-liga/zaragoza/1/5.jpg',
      '/images/la-liga/zaragoza/1/6.jpg',
    ],
    season: '2024/25',
  },

  // La Liga - Racing de Santander
  {
    id: 'racing-de-santander-1',
    team: 'Racing de Santander',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/racing-de-santander/1/1.jpg',
    images: [
      '/images/la-liga/racing-de-santander/1/1.jpg',
      '/images/la-liga/racing-de-santander/1/2.jpg',
      '/images/la-liga/racing-de-santander/1/3.jpg',
      '/images/la-liga/racing-de-santander/1/4.jpg',
      '/images/la-liga/racing-de-santander/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'racing-de-santander-2',
    team: 'Racing de Santander',
    league: 'la-liga',
    price: 32.99,
    image: '/images/la-liga/racing-de-santander/2/1.jpg',
    images: [
      '/images/la-liga/racing-de-santander/2/1.jpg',
      '/images/la-liga/racing-de-santander/2/2.jpg',
      '/images/la-liga/racing-de-santander/2/3.jpg',
      '/images/la-liga/racing-de-santander/2/4.jpg',
      '/images/la-liga/racing-de-santander/2/5.jpg',
      '/images/la-liga/racing-de-santander/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Premier League - Manchester United
  {
    id: 'manchester-united-1',
    team: 'Manchester United',
    league: 'premier-league',
    price: 35.99,
    image: '/images/premier-league/manchester-united/1/1.jpg',
    images: [
      '/images/premier-league/manchester-united/1/1.jpg',
      '/images/premier-league/manchester-united/1/2.jpg',
      '/images/premier-league/manchester-united/1/3.jpg',
      '/images/premier-league/manchester-united/1/4.jpg',
      '/images/premier-league/manchester-united/1/5.jpg',
      '/images/premier-league/manchester-united/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'manchester-united-2',
    team: 'Manchester United',
    league: 'premier-league',
    price: 35.99,
    image: '/images/premier-league/manchester-united/2/1.jpg',
    images: [
      '/images/premier-league/manchester-united/2/1.jpg',
      '/images/premier-league/manchester-united/2/2.jpg',
      '/images/premier-league/manchester-united/2/3.jpg',
      '/images/premier-league/manchester-united/2/4.jpg',
      '/images/premier-league/manchester-united/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Premier League - Tottenham
  {
    id: 'tottenham-1',
    team: 'Tottenham',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/tottenham/1/1.jpg',
    images: [
      '/images/premier-league/tottenham/1/1.jpg',
      '/images/premier-league/tottenham/1/2.jpg',
      '/images/premier-league/tottenham/1/3.jpg',
      '/images/premier-league/tottenham/1/4.jpg',
      '/images/premier-league/tottenham/1/5.jpg',
      '/images/premier-league/tottenham/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'tottenham-2',
    team: 'Tottenham',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/tottenham/2/1.jpg',
    images: [
      '/images/premier-league/tottenham/2/1.jpg',
      '/images/premier-league/tottenham/2/2.jpg',
      '/images/premier-league/tottenham/2/3.jpg',
      '/images/premier-league/tottenham/2/4.jpg',
      '/images/premier-league/tottenham/2/5.jpg',
      '/images/premier-league/tottenham/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Premier League - Newcastle
  {
    id: 'newcastle-1',
    team: 'Newcastle',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/newcastle/1/1.jpg',
    images: [
      '/images/premier-league/newcastle/1/1.jpg',
      '/images/premier-league/newcastle/1/2.jpg',
      '/images/premier-league/newcastle/1/3.jpg',
      '/images/premier-league/newcastle/1/4.jpg',
      '/images/premier-league/newcastle/1/5.jpg',
      '/images/premier-league/newcastle/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'newcastle-2',
    team: 'Newcastle',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/newcastle/2/1.jpg',
    images: [
      '/images/premier-league/newcastle/2/1.jpg',
      '/images/premier-league/newcastle/2/2.jpg',
      '/images/premier-league/newcastle/2/3.jpg',
      '/images/premier-league/newcastle/2/4.jpg',
      '/images/premier-league/newcastle/2/5.jpg',
      '/images/premier-league/newcastle/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Premier League - Leeds United
  {
    id: 'leeds-united-1',
    team: 'Leeds United',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/leeds-united/1/1.jpg',
    images: [
      '/images/premier-league/leeds-united/1/1.jpg',
      '/images/premier-league/leeds-united/1/2.jpg',
      '/images/premier-league/leeds-united/1/3.jpg',
      '/images/premier-league/leeds-united/1/4.jpg',
      '/images/premier-league/leeds-united/1/5.jpg',
      '/images/premier-league/leeds-united/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'leeds-united-2',
    team: 'Leeds United',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/leeds-united/2/1.jpg',
    images: [
      '/images/premier-league/leeds-united/2/1.jpg',
      '/images/premier-league/leeds-united/2/2.jpg',
      '/images/premier-league/leeds-united/2/3.jpg',
      '/images/premier-league/leeds-united/2/4.jpg',
      '/images/premier-league/leeds-united/2/5.jpg',
      '/images/premier-league/leeds-united/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Premier League - Everton
  {
    id: 'everton-1',
    team: 'Everton',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/everton/1/1.jpg',
    images: [
      '/images/premier-league/everton/1/1.jpg',
      '/images/premier-league/everton/1/2.jpg',
      '/images/premier-league/everton/1/3.jpg',
      '/images/premier-league/everton/1/4.jpg',
      '/images/premier-league/everton/1/5.jpg',
      '/images/premier-league/everton/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'everton-2',
    team: 'Everton',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/everton/2/1.jpg',
    images: [
      '/images/premier-league/everton/2/1.jpg',
      '/images/premier-league/everton/2/2.jpg',
      '/images/premier-league/everton/2/3.jpg',
      '/images/premier-league/everton/2/4.jpg',
      '/images/premier-league/everton/2/5.jpg',
      '/images/premier-league/everton/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Premier League - Brighton
  {
    id: 'brighton-1',
    team: 'Brighton',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/brighton/1/1.jpg',
    images: [
      '/images/premier-league/brighton/1/1.jpg',
      '/images/premier-league/brighton/1/2.jpg',
      '/images/premier-league/brighton/1/3.jpg',
      '/images/premier-league/brighton/1/4.jpg',
      '/images/premier-league/brighton/1/5.jpg',
      '/images/premier-league/brighton/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'brighton-2',
    team: 'Brighton',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/brighton/2/1.jpg',
    images: [
      '/images/premier-league/brighton/2/1.jpg',
      '/images/premier-league/brighton/2/2.jpg',
      '/images/premier-league/brighton/2/3.jpg',
      '/images/premier-league/brighton/2/4.jpg',
      '/images/premier-league/brighton/2/5.jpg',
      '/images/premier-league/brighton/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Premier League - Aston Villa
  {
    id: 'aston-villa-1',
    team: 'Aston Villa',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/aston-villa/1/1.jpg',
    images: [
      '/images/premier-league/aston-villa/1/1.jpg',
      '/images/premier-league/aston-villa/1/2.jpg',
      '/images/premier-league/aston-villa/1/3.jpg',
      '/images/premier-league/aston-villa/1/4.jpg',
      '/images/premier-league/aston-villa/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'aston-villa-2',
    team: 'Aston Villa',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/aston-villa/2/1.jpg',
    images: [
      '/images/premier-league/aston-villa/2/1.jpg',
      '/images/premier-league/aston-villa/2/2.jpg',
      '/images/premier-league/aston-villa/2/3.jpg',
      '/images/premier-league/aston-villa/2/4.jpg',
      '/images/premier-league/aston-villa/2/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'aston-villa-3',
    team: 'Aston Villa',
    league: 'premier-league',
    price: 32.99,
    image: '/images/premier-league/aston-villa/3/1.jpg',
    images: [
      '/images/premier-league/aston-villa/3/1.jpg',
      '/images/premier-league/aston-villa/3/2.jpg',
      '/images/premier-league/aston-villa/3/3.jpg',
      '/images/premier-league/aston-villa/3/4.jpg',
      '/images/premier-league/aston-villa/3/5.jpg',
      '/images/premier-league/aston-villa/3/6.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },

  // Bundesliga - Schalke 04
  {
    id: 'schalke-04-1',
    team: 'Schalke 04',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/schalke-04/1/1.jpg',
    images: [
      '/images/bundesliga/schalke-04/1/1.jpg',
      '/images/bundesliga/schalke-04/1/2.jpg',
      '/images/bundesliga/schalke-04/1/3.jpg',
      '/images/bundesliga/schalke-04/1/4.jpg',
      '/images/bundesliga/schalke-04/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Bundesliga - RB Leipzig
  {
    id: 'rb-leipzig-1',
    team: 'RB Leipzig',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/rb-leipzig/1/1.jpg',
    images: [
      '/images/bundesliga/rb-leipzig/1/1.jpg',
      '/images/bundesliga/rb-leipzig/1/2.jpg',
      '/images/bundesliga/rb-leipzig/1/3.jpg',
      '/images/bundesliga/rb-leipzig/1/4.jpg',
      '/images/bundesliga/rb-leipzig/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'rb-leipzig-2',
    team: 'RB Leipzig',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/rb-leipzig/2/1.jpg',
    images: [
      '/images/bundesliga/rb-leipzig/2/1.jpg',
      '/images/bundesliga/rb-leipzig/2/2.jpg',
      '/images/bundesliga/rb-leipzig/2/3.jpg',
      '/images/bundesliga/rb-leipzig/2/4.jpg',
      '/images/bundesliga/rb-leipzig/2/5.jpg',
      '/images/bundesliga/rb-leipzig/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Bundesliga - Wolfsburg
  {
    id: 'wolfsburg-1',
    team: 'Wolfsburg',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/wolfsburg/1/1.jpg',
    images: [
      '/images/bundesliga/wolfsburg/1/1.jpg',
      '/images/bundesliga/wolfsburg/1/2.jpg',
      '/images/bundesliga/wolfsburg/1/3.jpg',
      '/images/bundesliga/wolfsburg/1/4.jpg',
      '/images/bundesliga/wolfsburg/1/5.jpg',
      '/images/bundesliga/wolfsburg/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'wolfsburg-2',
    team: 'Wolfsburg',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/wolfsburg/2/1.jpg',
    images: [
      '/images/bundesliga/wolfsburg/2/1.jpg',
      '/images/bundesliga/wolfsburg/2/2.jpg',
      '/images/bundesliga/wolfsburg/2/3.jpg',
      '/images/bundesliga/wolfsburg/2/4.jpg',
      '/images/bundesliga/wolfsburg/2/5.jpg',
      '/images/bundesliga/wolfsburg/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Bundesliga - Eintracht Frankfurt
  {
    id: 'eintracht-frankfurt-1',
    team: 'Eintracht Frankfurt',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/eintracht-frankfurt/1/1.jpg',
    images: [
      '/images/bundesliga/eintracht-frankfurt/1/1.jpg',
      '/images/bundesliga/eintracht-frankfurt/1/2.jpg',
      '/images/bundesliga/eintracht-frankfurt/1/3.jpg',
      '/images/bundesliga/eintracht-frankfurt/1/4.jpg',
      '/images/bundesliga/eintracht-frankfurt/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Bundesliga - Borussia Mönchengladbach
  {
    id: 'borussia-monchengladbach-1',
    team: 'Borussia Mönchengladbach',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/borussia-monchengladbach/1/1.jpg',
    images: [
      '/images/bundesliga/borussia-monchengladbach/1/1.jpg',
      '/images/bundesliga/borussia-monchengladbach/1/2.jpg',
      '/images/bundesliga/borussia-monchengladbach/1/3.jpg',
      '/images/bundesliga/borussia-monchengladbach/1/4.jpg',
      '/images/bundesliga/borussia-monchengladbach/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'borussia-monchengladbach-2',
    team: 'Borussia Mönchengladbach',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/borussia-monchengladbach/2/1.jpg',
    images: [
      '/images/bundesliga/borussia-monchengladbach/2/1.jpg',
      '/images/bundesliga/borussia-monchengladbach/2/2.jpg',
      '/images/bundesliga/borussia-monchengladbach/2/3.jpg',
      '/images/bundesliga/borussia-monchengladbach/2/4.jpg',
      '/images/bundesliga/borussia-monchengladbach/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Bundesliga - Stuttgart
  {
    id: 'stuttgart-1',
    team: 'Stuttgart',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/stuttgart/1/1.jpg',
    images: [
      '/images/bundesliga/stuttgart/1/1.jpg',
      '/images/bundesliga/stuttgart/1/2.jpg',
      '/images/bundesliga/stuttgart/1/3.jpg',
      '/images/bundesliga/stuttgart/1/4.jpg',
      '/images/bundesliga/stuttgart/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'stuttgart-2',
    team: 'Stuttgart',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/stuttgart/2/1.jpg',
    images: [
      '/images/bundesliga/stuttgart/2/1.jpg',
      '/images/bundesliga/stuttgart/2/2.jpg',
      '/images/bundesliga/stuttgart/2/3.jpg',
      '/images/bundesliga/stuttgart/2/4.jpg',
      '/images/bundesliga/stuttgart/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Bundesliga - FC Union Berlin
  {
    id: 'fc-union-berlin-1',
    team: 'FC Union Berlin',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/fc-union-berlin/1/1.jpg',
    images: [
      '/images/bundesliga/fc-union-berlin/1/1.jpg',
      '/images/bundesliga/fc-union-berlin/1/2.jpg',
      '/images/bundesliga/fc-union-berlin/1/3.jpg',
      '/images/bundesliga/fc-union-berlin/1/4.jpg',
      '/images/bundesliga/fc-union-berlin/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'fc-union-berlin-2',
    team: 'FC Union Berlin',
    league: 'bundesliga',
    price: 32.99,
    image: '/images/bundesliga/fc-union-berlin/2/1.jpg',
    images: [
      '/images/bundesliga/fc-union-berlin/2/1.jpg',
      '/images/bundesliga/fc-union-berlin/2/2.jpg',
      '/images/bundesliga/fc-union-berlin/2/3.jpg',
      '/images/bundesliga/fc-union-berlin/2/4.jpg',
      '/images/bundesliga/fc-union-berlin/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Ligue 1 - Olympique Lyon
  {
    id: 'olympique-lyon-1',
    team: 'Olympique Lyon',
    league: 'ligue-1',
    price: 32.99,
    image: '/images/ligue-1/olympique-lyon/1/1.jpg',
    images: [
      '/images/ligue-1/olympique-lyon/1/1.jpg',
      '/images/ligue-1/olympique-lyon/1/2.jpg',
      '/images/ligue-1/olympique-lyon/1/3.jpg',
      '/images/ligue-1/olympique-lyon/1/4.jpg',
      '/images/ligue-1/olympique-lyon/1/5.jpg',
      '/images/ligue-1/olympique-lyon/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'olympique-lyon-2',
    team: 'Olympique Lyon',
    league: 'ligue-1',
    price: 32.99,
    image: '/images/ligue-1/olympique-lyon/2/1.jpg',
    images: [
      '/images/ligue-1/olympique-lyon/2/1.jpg',
      '/images/ligue-1/olympique-lyon/2/2.jpg',
      '/images/ligue-1/olympique-lyon/2/3.jpg',
      '/images/ligue-1/olympique-lyon/2/4.jpg',
      '/images/ligue-1/olympique-lyon/2/5.jpg',
      '/images/ligue-1/olympique-lyon/2/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'olympique-lyon-3',
    team: 'Olympique Lyon',
    league: 'ligue-1',
    price: 32.99,
    image: '/images/ligue-1/olympique-lyon/3/1.jpg',
    images: [
      '/images/ligue-1/olympique-lyon/3/1.jpg',
      '/images/ligue-1/olympique-lyon/3/2.jpg',
      '/images/ligue-1/olympique-lyon/3/3.jpg',
      '/images/ligue-1/olympique-lyon/3/4.jpg',
      '/images/ligue-1/olympique-lyon/3/5.jpg',
      '/images/ligue-1/olympique-lyon/3/6.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },

  // Ligue 1 - Lille
  {
    id: 'lille-1',
    team: 'Lille',
    league: 'ligue-1',
    price: 32.99,
    image: '/images/ligue-1/lille/1/1.jpg',
    images: [
      '/images/ligue-1/lille/1/1.jpg',
      '/images/ligue-1/lille/1/2.jpg',
      '/images/ligue-1/lille/1/3.jpg',
      '/images/ligue-1/lille/1/4.jpg',
      '/images/ligue-1/lille/1/5.jpg',
      '/images/ligue-1/lille/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'lille-2',
    team: 'Lille',
    league: 'ligue-1',
    price: 32.99,
    image: '/images/ligue-1/lille/2/1.jpg',
    images: [
      '/images/ligue-1/lille/2/1.jpg',
      '/images/ligue-1/lille/2/2.jpg',
      '/images/ligue-1/lille/2/3.jpg',
      '/images/ligue-1/lille/2/4.jpg',
      '/images/ligue-1/lille/2/5.jpg',
      '/images/ligue-1/lille/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Ligue 1 - Stade Rennais
  {
    id: 'stade-rennais-1',
    team: 'Stade Rennais',
    league: 'ligue-1',
    price: 32.99,
    image: '/images/ligue-1/stade-rennais/1/1.jpg',
    images: [
      '/images/ligue-1/stade-rennais/1/1.jpg',
      '/images/ligue-1/stade-rennais/1/2.jpg',
      '/images/ligue-1/stade-rennais/1/3.jpg',
      '/images/ligue-1/stade-rennais/1/4.jpg',
      '/images/ligue-1/stade-rennais/1/5.jpg',
      '/images/ligue-1/stade-rennais/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Serie A - Roma
  {
    id: 'roma-1',
    team: 'Roma',
    league: 'serie-a',
    price: 32.99,
    image: '/images/serie-a/roma/1/1.jpg',
    images: [
      '/images/serie-a/roma/1/1.jpg',
      '/images/serie-a/roma/1/2.jpg',
      '/images/serie-a/roma/1/3.jpg',
      '/images/serie-a/roma/1/4.jpg',
      '/images/serie-a/roma/1/5.jpg',
      '/images/serie-a/roma/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'roma-2',
    team: 'Roma',
    league: 'serie-a',
    price: 32.99,
    image: '/images/serie-a/roma/2/1.jpg',
    images: [
      '/images/serie-a/roma/2/1.jpg',
      '/images/serie-a/roma/2/2.jpg',
      '/images/serie-a/roma/2/3.jpg',
      '/images/serie-a/roma/2/4.jpg',
      '/images/serie-a/roma/2/5.jpg',
      '/images/serie-a/roma/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Serie A - Fiorentina
  {
    id: 'fiorentina-1',
    team: 'Fiorentina',
    league: 'serie-a',
    price: 32.99,
    image: '/images/serie-a/fiorentina/1/1.jpg',
    images: [
      '/images/serie-a/fiorentina/1/1.jpg',
      '/images/serie-a/fiorentina/1/2.jpg',
      '/images/serie-a/fiorentina/1/3.jpg',
      '/images/serie-a/fiorentina/1/4.jpg',
      '/images/serie-a/fiorentina/1/5.jpg',
      '/images/serie-a/fiorentina/1/6.jpg',
      '/images/serie-a/fiorentina/1/7.jpg',
      '/images/serie-a/fiorentina/1/8.jpg',
    ],
    season: '2024/25',
  },

  // Serie A - Atalanta
  {
    id: 'atalanta-1',
    team: 'Atalanta',
    league: 'serie-a',
    price: 32.99,
    image: '/images/serie-a/atalanta/1/1.jpg',
    images: [
      '/images/serie-a/atalanta/1/1.jpg',
      '/images/serie-a/atalanta/1/2.jpg',
      '/images/serie-a/atalanta/1/3.jpg',
      '/images/serie-a/atalanta/1/4.jpg',
      '/images/serie-a/atalanta/1/5.jpg',
      '/images/serie-a/atalanta/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'atalanta-2',
    team: 'Atalanta',
    league: 'serie-a',
    price: 32.99,
    image: '/images/serie-a/atalanta/2/1.jpg',
    images: [
      '/images/serie-a/atalanta/2/1.jpg',
      '/images/serie-a/atalanta/2/2.jpg',
      '/images/serie-a/atalanta/2/3.jpg',
      '/images/serie-a/atalanta/2/4.jpg',
      '/images/serie-a/atalanta/2/5.jpg',
      '/images/serie-a/atalanta/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Serie A - Lazio
  {
    id: 'lazio-1',
    team: 'Lazio',
    league: 'serie-a',
    price: 32.99,
    image: '/images/serie-a/lazio/1/1.jpg',
    images: [
      '/images/serie-a/lazio/1/1.jpg',
      '/images/serie-a/lazio/1/2.jpg',
      '/images/serie-a/lazio/1/3.jpg',
      '/images/serie-a/lazio/1/4.jpg',
      '/images/serie-a/lazio/1/5.jpg',
      '/images/serie-a/lazio/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Serie A - Parma
  {
    id: 'parma-1',
    team: 'Parma',
    league: 'serie-a',
    price: 32.99,
    image: '/images/serie-a/parma/1/1.jpg',
    images: [
      '/images/serie-a/parma/1/1.jpg',
      '/images/serie-a/parma/1/2.jpg',
      '/images/serie-a/parma/1/3.jpg',
      '/images/serie-a/parma/1/4.jpg',
      '/images/serie-a/parma/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Brasileirão - Corinthians
  {
    id: 'corinthians-1',
    team: 'Corinthians',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/corinthians/1/1.jpg',
    images: [
      '/images/brasileirao/corinthians/1/1.jpg',
      '/images/brasileirao/corinthians/1/2.jpg',
      '/images/brasileirao/corinthians/1/3.jpg',
      '/images/brasileirao/corinthians/1/4.jpg',
      '/images/brasileirao/corinthians/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'corinthians-2',
    team: 'Corinthians',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/corinthians/2/1.jpg',
    images: [
      '/images/brasileirao/corinthians/2/1.jpg',
      '/images/brasileirao/corinthians/2/2.jpg',
      '/images/brasileirao/corinthians/2/3.jpg',
      '/images/brasileirao/corinthians/2/4.jpg',
      '/images/brasileirao/corinthians/2/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'corinthians-3',
    team: 'Corinthians',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/corinthians/3/1.jpg',
    images: [
      '/images/brasileirao/corinthians/3/1.jpg',
      '/images/brasileirao/corinthians/3/2.jpg',
      '/images/brasileirao/corinthians/3/3.jpg',
      '/images/brasileirao/corinthians/3/4.jpg',
      '/images/brasileirao/corinthians/3/5.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },

  // Brasileirão - Internacional
  {
    id: 'internacional-1',
    team: 'Internacional',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/internacional/1/1.jpg',
    images: [
      '/images/brasileirao/internacional/1/1.jpg',
      '/images/brasileirao/internacional/1/2.jpg',
      '/images/brasileirao/internacional/1/3.jpg',
      '/images/brasileirao/internacional/1/4.jpg',
      '/images/brasileirao/internacional/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'internacional-2',
    team: 'Internacional',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/internacional/2/1.jpg',
    images: [
      '/images/brasileirao/internacional/2/1.jpg',
      '/images/brasileirao/internacional/2/2.jpg',
      '/images/brasileirao/internacional/2/3.jpg',
      '/images/brasileirao/internacional/2/4.jpg',
      '/images/brasileirao/internacional/2/5.jpg',
      '/images/brasileirao/internacional/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Brasileirão - Fluminense
  {
    id: 'fluminense-1',
    team: 'Fluminense',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/fluminense/1/1.jpg',
    images: [
      '/images/brasileirao/fluminense/1/1.jpg',
      '/images/brasileirao/fluminense/1/2.jpg',
      '/images/brasileirao/fluminense/1/3.jpg',
      '/images/brasileirao/fluminense/1/4.jpg',
      '/images/brasileirao/fluminense/1/5.jpg',
      '/images/brasileirao/fluminense/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'fluminense-2',
    team: 'Fluminense',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/fluminense/2/1.jpg',
    images: [
      '/images/brasileirao/fluminense/2/1.jpg',
      '/images/brasileirao/fluminense/2/2.jpg',
      '/images/brasileirao/fluminense/2/3.jpg',
      '/images/brasileirao/fluminense/2/4.jpg',
      '/images/brasileirao/fluminense/2/5.jpg',
      '/images/brasileirao/fluminense/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Brasileirão - Cruzeiro
  {
    id: 'cruzeiro-1',
    team: 'Cruzeiro',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/cruzeiro/1/1.jpg',
    images: [
      '/images/brasileirao/cruzeiro/1/1.jpg',
      '/images/brasileirao/cruzeiro/1/2.jpg',
      '/images/brasileirao/cruzeiro/1/3.jpg',
      '/images/brasileirao/cruzeiro/1/4.jpg',
      '/images/brasileirao/cruzeiro/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'cruzeiro-2',
    team: 'Cruzeiro',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/cruzeiro/2/1.jpg',
    images: [
      '/images/brasileirao/cruzeiro/2/1.jpg',
      '/images/brasileirao/cruzeiro/2/2.jpg',
      '/images/brasileirao/cruzeiro/2/3.jpg',
      '/images/brasileirao/cruzeiro/2/4.jpg',
      '/images/brasileirao/cruzeiro/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Brasileirão - Vasco Da Gama
  {
    id: 'vasco-da-gama-1',
    team: 'Vasco Da Gama',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/vasco-da-gama/1/1.jpg',
    images: [
      '/images/brasileirao/vasco-da-gama/1/1.jpg',
      '/images/brasileirao/vasco-da-gama/1/2.jpg',
      '/images/brasileirao/vasco-da-gama/1/3.jpg',
      '/images/brasileirao/vasco-da-gama/1/4.jpg',
      '/images/brasileirao/vasco-da-gama/1/5.jpg',
      '/images/brasileirao/vasco-da-gama/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'vasco-da-gama-2',
    team: 'Vasco Da Gama',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/vasco-da-gama/2/1.jpg',
    images: [
      '/images/brasileirao/vasco-da-gama/2/1.jpg',
      '/images/brasileirao/vasco-da-gama/2/2.jpg',
      '/images/brasileirao/vasco-da-gama/2/3.jpg',
      '/images/brasileirao/vasco-da-gama/2/4.jpg',
      '/images/brasileirao/vasco-da-gama/2/5.jpg',
      '/images/brasileirao/vasco-da-gama/2/6.jpg',
    ],
    season: '2024/25',
  },

  // Brasileirão - São Paulo
  {
    id: 'sao-paulo-1',
    team: 'São Paulo',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/sao-paulo/1/1.jpg',
    images: [
      '/images/brasileirao/sao-paulo/1/1.jpg',
      '/images/brasileirao/sao-paulo/1/2.jpg',
      '/images/brasileirao/sao-paulo/1/3.jpg',
      '/images/brasileirao/sao-paulo/1/4.jpg',
      '/images/brasileirao/sao-paulo/1/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'sao-paulo-2',
    team: 'São Paulo',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/sao-paulo/2/1.jpg',
    images: [
      '/images/brasileirao/sao-paulo/2/1.jpg',
      '/images/brasileirao/sao-paulo/2/2.jpg',
      '/images/brasileirao/sao-paulo/2/3.jpg',
      '/images/brasileirao/sao-paulo/2/4.jpg',
      '/images/brasileirao/sao-paulo/2/5.jpg',
    ],
    season: '2024/25',
  },

  // Brasileirão - Atlético Mineiro
  {
    id: 'atletico-mineiro-1',
    team: 'Atlético Mineiro',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/atletico-mineiro/1/1.jpg',
    images: [
      '/images/brasileirao/atletico-mineiro/1/1.jpg',
      '/images/brasileirao/atletico-mineiro/1/2.jpg',
      '/images/brasileirao/atletico-mineiro/1/3.jpg',
      '/images/brasileirao/atletico-mineiro/1/4.jpg',
      '/images/brasileirao/atletico-mineiro/1/5.jpg',
      '/images/brasileirao/atletico-mineiro/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'atletico-mineiro-2',
    team: 'Atlético Mineiro',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/atletico-mineiro/2/1.jpg',
    images: [
      '/images/brasileirao/atletico-mineiro/2/1.jpg',
      '/images/brasileirao/atletico-mineiro/2/2.jpg',
      '/images/brasileirao/atletico-mineiro/2/3.jpg',
      '/images/brasileirao/atletico-mineiro/2/4.jpg',
      '/images/brasileirao/atletico-mineiro/2/5.jpg',
      '/images/brasileirao/atletico-mineiro/2/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'atletico-mineiro-3',
    team: 'Atlético Mineiro',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/atletico-mineiro/3/1.jpg',
    images: [
      '/images/brasileirao/atletico-mineiro/3/1.jpg',
      '/images/brasileirao/atletico-mineiro/3/2.jpg',
      '/images/brasileirao/atletico-mineiro/3/3.jpg',
      '/images/brasileirao/atletico-mineiro/3/4.jpg',
      '/images/brasileirao/atletico-mineiro/3/5.jpg',
      '/images/brasileirao/atletico-mineiro/3/6.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },

  // Brasileirão - Botafogo
  {
    id: 'botafogo-1',
    team: 'Botafogo',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/botafogo/1/1.jpg',
    images: [
      '/images/brasileirao/botafogo/1/1.jpg',
      '/images/brasileirao/botafogo/1/2.jpg',
      '/images/brasileirao/botafogo/1/3.jpg',
      '/images/brasileirao/botafogo/1/4.jpg',
      '/images/brasileirao/botafogo/1/5.jpg',
      '/images/brasileirao/botafogo/1/6.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'botafogo-2',
    team: 'Botafogo',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/botafogo/2/1.jpg',
    images: [
      '/images/brasileirao/botafogo/2/1.jpg',
      '/images/brasileirao/botafogo/2/2.jpg',
      '/images/brasileirao/botafogo/2/3.jpg',
      '/images/brasileirao/botafogo/2/4.jpg',
      '/images/brasileirao/botafogo/2/5.jpg',
    ],
    season: '2024/25',
  },
  {
    id: 'botafogo-3',
    team: 'Botafogo',
    league: 'brasileirao',
    price: 32.99,
    image: '/images/brasileirao/botafogo/3/1.jpg',
    images: [
      '/images/brasileirao/botafogo/3/1.jpg',
      '/images/brasileirao/botafogo/3/2.jpg',
      '/images/brasileirao/botafogo/3/3.jpg',
      '/images/brasileirao/botafogo/3/4.jpg',
      '/images/brasileirao/botafogo/3/5.jpg',
      '/images/brasileirao/botafogo/3/6.jpg',
    ],
    season: '2024/25',
    isNew: true,
  },

  // Selecciones - Noruega
  {
    id: 'noruega-1',
    team: 'Noruega',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/noruega/1/1.jpg',
    images: [
      '/images/selecciones/noruega/1/1.jpg',
      '/images/selecciones/noruega/1/2.jpg',
      '/images/selecciones/noruega/1/3.jpg',
      '/images/selecciones/noruega/1/4.jpg',
      '/images/selecciones/noruega/1/5.jpg',
      '/images/selecciones/noruega/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Bolivia
  {
    id: 'bolivia-1',
    team: 'Bolivia',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/bolivia/1/1.jpg',
    images: [
      '/images/selecciones/bolivia/1/1.jpg',
      '/images/selecciones/bolivia/1/2.jpg',
      '/images/selecciones/bolivia/1/3.jpg',
      '/images/selecciones/bolivia/1/4.jpg',
      '/images/selecciones/bolivia/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - México
  {
    id: 'mexico-1',
    team: 'México',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/mexico/1/1.jpg',
    images: [
      '/images/selecciones/mexico/1/1.jpg',
      '/images/selecciones/mexico/1/2.jpg',
      '/images/selecciones/mexico/1/3.jpg',
      '/images/selecciones/mexico/1/4.jpg',
      '/images/selecciones/mexico/1/5.jpg',
      '/images/selecciones/mexico/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Japón
  {
    id: 'japon-1',
    team: 'Japón',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/japon/1/1.jpg',
    images: [
      '/images/selecciones/japon/1/1.jpg',
      '/images/selecciones/japon/1/2.jpg',
      '/images/selecciones/japon/1/3.jpg',
      '/images/selecciones/japon/1/4.jpg',
      '/images/selecciones/japon/1/5.jpg',
      '/images/selecciones/japon/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Colombia
  {
    id: 'colombia-1',
    team: 'Colombia',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/colombia/1/1.jpg',
    images: [
      '/images/selecciones/colombia/1/1.jpg',
      '/images/selecciones/colombia/1/2.jpg',
      '/images/selecciones/colombia/1/3.jpg',
      '/images/selecciones/colombia/1/4.jpg',
      '/images/selecciones/colombia/1/5.jpg',
      '/images/selecciones/colombia/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Holanda
  {
    id: 'holanda-1',
    team: 'Holanda',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/holanda/1/1.jpg',
    images: [
      '/images/selecciones/holanda/1/1.jpg',
      '/images/selecciones/holanda/1/2.jpg',
      '/images/selecciones/holanda/1/3.jpg',
      '/images/selecciones/holanda/1/4.jpg',
      '/images/selecciones/holanda/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Jamaica
  {
    id: 'jamaica-1',
    team: 'Jamaica',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/jamaica/1/1.jpg',
    images: [
      '/images/selecciones/jamaica/1/1.jpg',
      '/images/selecciones/jamaica/1/2.jpg',
      '/images/selecciones/jamaica/1/3.jpg',
      '/images/selecciones/jamaica/1/4.jpg',
      '/images/selecciones/jamaica/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - EEUU
  {
    id: 'eeuu-1',
    team: 'EEUU',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/eeuu/1/1.jpg',
    images: [
      '/images/selecciones/eeuu/1/1.jpg',
      '/images/selecciones/eeuu/1/2.jpg',
      '/images/selecciones/eeuu/1/3.jpg',
      '/images/selecciones/eeuu/1/4.jpg',
      '/images/selecciones/eeuu/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Portugal
  {
    id: 'portugal-1',
    team: 'Portugal',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/portugal/1/1.jpg',
    images: [
      '/images/selecciones/portugal/1/1.jpg',
      '/images/selecciones/portugal/1/2.jpg',
      '/images/selecciones/portugal/1/3.jpg',
      '/images/selecciones/portugal/1/4.jpg',
      '/images/selecciones/portugal/1/5.jpg',
      '/images/selecciones/portugal/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Perú
  {
    id: 'peru-1',
    team: 'Perú',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/peru/1/1.jpg',
    images: [
      '/images/selecciones/peru/1/1.jpg',
      '/images/selecciones/peru/1/2.jpg',
      '/images/selecciones/peru/1/3.jpg',
      '/images/selecciones/peru/1/4.jpg',
      '/images/selecciones/peru/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Suecia
  {
    id: 'suecia-1',
    team: 'Suecia',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/suecia/1/1.jpg',
    images: [
      '/images/selecciones/suecia/1/1.jpg',
      '/images/selecciones/suecia/1/2.jpg',
      '/images/selecciones/suecia/1/3.jpg',
      '/images/selecciones/suecia/1/4.jpg',
      '/images/selecciones/suecia/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Grecia
  {
    id: 'grecia-1',
    team: 'Grecia',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/grecia/1/1.jpg',
    images: [
      '/images/selecciones/grecia/1/1.jpg',
      '/images/selecciones/grecia/1/2.jpg',
      '/images/selecciones/grecia/1/3.jpg',
      '/images/selecciones/grecia/1/4.jpg',
      '/images/selecciones/grecia/1/5.jpg',
      '/images/selecciones/grecia/1/6.jpg',
      '/images/selecciones/grecia/1/7.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Venezuela
  {
    id: 'venezuela-1',
    team: 'Venezuela',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/venezuela/1/1.jpg',
    images: [
      '/images/selecciones/venezuela/1/1.jpg',
      '/images/selecciones/venezuela/1/2.jpg',
      '/images/selecciones/venezuela/1/3.jpg',
      '/images/selecciones/venezuela/1/4.jpg',
      '/images/selecciones/venezuela/1/5.jpg',
      '/images/selecciones/venezuela/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Croacia
  {
    id: 'croacia-1',
    team: 'Croacia',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/croacia/1/1.jpg',
    images: [
      '/images/selecciones/croacia/1/1.jpg',
      '/images/selecciones/croacia/1/2.jpg',
      '/images/selecciones/croacia/1/3.jpg',
      '/images/selecciones/croacia/1/4.jpg',
      '/images/selecciones/croacia/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Marruecos
  {
    id: 'marruecos-1',
    team: 'Marruecos',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/marruecos/1/1.jpg',
    images: [
      '/images/selecciones/marruecos/1/1.jpg',
      '/images/selecciones/marruecos/1/2.jpg',
      '/images/selecciones/marruecos/1/3.jpg',
      '/images/selecciones/marruecos/1/4.jpg',
      '/images/selecciones/marruecos/1/5.jpg',
      '/images/selecciones/marruecos/1/6.jpg',
    ],
    season: '2024/25',
  },

  // Selecciones - Uruguay
  {
    id: 'uruguay-1',
    team: 'Uruguay',
    league: 'selecciones',
    price: 32.99,
    image: '/images/selecciones/uruguay/1/1.jpg',
    images: [
      '/images/selecciones/uruguay/1/1.jpg',
      '/images/selecciones/uruguay/1/2.jpg',
      '/images/selecciones/uruguay/1/3.jpg',
      '/images/selecciones/uruguay/1/4.jpg',
      '/images/selecciones/uruguay/1/5.jpg',
    ],
    season: '2024/25',
  },

  // Retro - Real Madrid
  {
    id: 'retro-real-madrid-1',
    team: 'Real Madrid',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/real-madrid/1/1.jpg',
    images: [
      '/images/retro/real-madrid/1/1.jpg',
      '/images/retro/real-madrid/1/2.jpg',
      '/images/retro/real-madrid/1/3.jpg',
      '/images/retro/real-madrid/1/4.jpg',
      '/images/retro/real-madrid/1/5.jpg',
    ],
    season: 'Retro',
  },
  {
    id: 'retro-real-madrid-2',
    team: 'Real Madrid',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/real-madrid/2/1.jpg',
    images: [
      '/images/retro/real-madrid/2/1.jpg',
      '/images/retro/real-madrid/2/2.jpg',
      '/images/retro/real-madrid/2/3.jpg',
      '/images/retro/real-madrid/2/4.jpg',
      '/images/retro/real-madrid/2/5.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Barcelona
  {
    id: 'retro-barcelona-1',
    team: 'FC Barcelona',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/barcelona/1/1.jpg',
    images: [
      '/images/retro/barcelona/1/1.jpg',
      '/images/retro/barcelona/1/2.jpg',
      '/images/retro/barcelona/1/3.jpg',
      '/images/retro/barcelona/1/4.jpg',
      '/images/retro/barcelona/1/5.jpg',
    ],
    season: 'Retro',
  },
  {
    id: 'retro-barcelona-2',
    team: 'FC Barcelona',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/barcelona/2/1.jpg',
    images: [
      '/images/retro/barcelona/2/1.jpg',
      '/images/retro/barcelona/2/2.jpg',
      '/images/retro/barcelona/2/3.jpg',
      '/images/retro/barcelona/2/4.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Arsenal
  {
    id: 'retro-arsenal-1',
    team: 'Arsenal FC',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/arsenal/1/1.jpg',
    images: [
      '/images/retro/arsenal/1/1.jpg',
      '/images/retro/arsenal/1/2.jpg',
      '/images/retro/arsenal/1/3.jpg',
      '/images/retro/arsenal/1/4.jpg',
      '/images/retro/arsenal/1/5.jpg',
    ],
    season: 'Retro',
  },
  {
    id: 'retro-arsenal-2',
    team: 'Arsenal FC',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/arsenal/2/1.jpg',
    images: [
      '/images/retro/arsenal/2/1.jpg',
      '/images/retro/arsenal/2/2.jpg',
      '/images/retro/arsenal/2/3.jpg',
      '/images/retro/arsenal/2/4.jpg',
      '/images/retro/arsenal/2/5.jpg',
    ],
    season: 'Retro',
  },
  {
    id: 'retro-arsenal-3',
    team: 'Arsenal FC',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/arsenal/3/1.jpg',
    images: [
      '/images/retro/arsenal/3/1.jpg',
      '/images/retro/arsenal/3/2.jpg',
      '/images/retro/arsenal/3/3.jpg',
      '/images/retro/arsenal/3/4.jpg',
      '/images/retro/arsenal/3/5.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Ajax
  {
    id: 'retro-ajax-1',
    team: 'Ajax',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/ajax/1/1.jpg',
    images: [
      '/images/retro/ajax/1/1.jpg',
      '/images/retro/ajax/1/2.jpg',
      '/images/retro/ajax/1/3.jpg',
      '/images/retro/ajax/1/4.jpg',
      '/images/retro/ajax/1/5.jpg',
      '/images/retro/ajax/1/6.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Inter Milan
  {
    id: 'retro-inter-milan-1',
    team: 'Inter Milan',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/inter-milan/1/1.jpg',
    images: [
      '/images/retro/inter-milan/1/1.jpg',
      '/images/retro/inter-milan/1/2.jpg',
      '/images/retro/inter-milan/1/3.jpg',
      '/images/retro/inter-milan/1/4.jpg',
      '/images/retro/inter-milan/1/5.jpg',
    ],
    season: 'Retro',
  },

  // Retro - AC Milan
  {
    id: 'retro-milan-1',
    team: 'AC Milan',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/milan/1/1.jpg',
    images: [
      '/images/retro/milan/1/1.jpg',
      '/images/retro/milan/1/2.jpg',
      '/images/retro/milan/1/3.jpg',
      '/images/retro/milan/1/4.jpg',
      '/images/retro/milan/1/5.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Parma
  {
    id: 'retro-parma-1',
    team: 'Parma',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/parma/1/1.jpg',
    images: [
      '/images/retro/parma/1/1.jpg',
      '/images/retro/parma/1/2.jpg',
      '/images/retro/parma/1/3.jpg',
      '/images/retro/parma/1/4.jpg',
      '/images/retro/parma/1/5.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Argentina
  {
    id: 'retro-argentina-1',
    team: 'Argentina',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/argentina/1/1.jpg',
    images: [
      '/images/retro/argentina/1/1.jpg',
      '/images/retro/argentina/1/2.jpg',
      '/images/retro/argentina/1/3.jpg',
      '/images/retro/argentina/1/4.jpg',
      '/images/retro/argentina/1/5.jpg',
    ],
    season: 'Retro',
  },
  {
    id: 'retro-argentina-2',
    team: 'Argentina',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/argentina/2/1.jpg',
    images: [
      '/images/retro/argentina/2/1.jpg',
      '/images/retro/argentina/2/2.jpg',
      '/images/retro/argentina/2/3.jpg',
      '/images/retro/argentina/2/4.jpg',
      '/images/retro/argentina/2/5.jpg',
    ],
    season: 'Retro',
  },
  {
    id: 'retro-argentina-3',
    team: 'Argentina',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/argentina/3/1.jpg',
    images: [
      '/images/retro/argentina/3/1.jpg',
      '/images/retro/argentina/3/2.jpg',
      '/images/retro/argentina/3/3.jpg',
      '/images/retro/argentina/3/4.jpg',
      '/images/retro/argentina/3/5.jpg',
      '/images/retro/argentina/3/6.jpg',
    ],
    season: 'Retro',
  },
  {
    id: 'retro-argentina-4',
    team: 'Argentina',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/argentina/4/1.jpg',
    images: [
      '/images/retro/argentina/4/1.jpg',
      '/images/retro/argentina/4/2.jpg',
      '/images/retro/argentina/4/3.jpg',
      '/images/retro/argentina/4/4.jpg',
      '/images/retro/argentina/4/5.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Alemania
  {
    id: 'retro-alemania-1',
    team: 'Alemania',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/alemania/1/1.jpg',
    images: [
      '/images/retro/alemania/1/1.jpg',
      '/images/retro/alemania/1/2.jpg',
      '/images/retro/alemania/1/3.jpg',
      '/images/retro/alemania/1/4.jpg',
      '/images/retro/alemania/1/5.jpg',
    ],
    season: 'Retro',
  },
  {
    id: 'retro-alemania-2',
    team: 'Alemania',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/alemania/2/1.jpg',
    images: [
      '/images/retro/alemania/2/1.jpg',
      '/images/retro/alemania/2/2.jpg',
      '/images/retro/alemania/2/3.jpg',
      '/images/retro/alemania/2/4.jpg',
      '/images/retro/alemania/2/5.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Francia
  {
    id: 'retro-francia-1',
    team: 'Francia',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/francia/1/1.jpg',
    images: [
      '/images/retro/francia/1/1.jpg',
      '/images/retro/francia/1/2.jpg',
      '/images/retro/francia/1/3.jpg',
      '/images/retro/francia/1/4.jpg',
      '/images/retro/francia/1/5.jpg',
    ],
    season: 'Retro',
  },
  {
    id: 'retro-francia-2',
    team: 'Francia',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/francia/2/1.jpg',
    images: [
      '/images/retro/francia/2/1.jpg',
      '/images/retro/francia/2/2.jpg',
      '/images/retro/francia/2/3.jpg',
      '/images/retro/francia/2/4.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Holanda
  {
    id: 'retro-holanda-1',
    team: 'Holanda',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/holanda/1/1.jpg',
    images: [
      '/images/retro/holanda/1/1.jpg',
      '/images/retro/holanda/1/2.jpg',
      '/images/retro/holanda/1/3.jpg',
      '/images/retro/holanda/1/4.jpg',
      '/images/retro/holanda/1/5.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Brasil
  {
    id: 'retro-brasil-1',
    team: 'Brasil',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/brasil/1/1.jpg',
    images: [
      '/images/retro/brasil/1/1.jpg',
      '/images/retro/brasil/1/2.jpg',
      '/images/retro/brasil/1/3.jpg',
      '/images/retro/brasil/1/4.jpg',
      '/images/retro/brasil/1/5.jpg',
    ],
    season: 'Retro',
  },
  {
    id: 'retro-brasil-2',
    team: 'Brasil',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/brasil/2/1.jpg',
    images: [
      '/images/retro/brasil/2/1.jpg',
      '/images/retro/brasil/2/2.jpg',
      '/images/retro/brasil/2/3.jpg',
      '/images/retro/brasil/2/4.jpg',
      '/images/retro/brasil/2/5.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Japón
  {
    id: 'retro-japon-1',
    team: 'Japón',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/japon/1/1.jpg',
    images: [
      '/images/retro/japon/1/1.jpg',
      '/images/retro/japon/1/2.jpg',
      '/images/retro/japon/1/3.jpg',
      '/images/retro/japon/1/4.jpg',
    ],
    season: 'Retro',
  },

  // Retro - Napoli
  {
    id: 'retro-napoli-1',
    team: 'Napoli',
    league: 'retro',
    price: 38.99,
    image: '/images/retro/napoli/1/1.jpg',
    images: [
      '/images/retro/napoli/1/1.jpg',
      '/images/retro/napoli/1/2.jpg',
      '/images/retro/napoli/1/3.jpg',
      '/images/retro/napoli/1/4.jpg',
      '/images/retro/napoli/1/5.jpg',
      '/images/retro/napoli/1/6.jpg',
    ],
    season: 'Retro',
  },
];

export function getJerseysByLeague(league: League): Jersey[] {
  return jerseys.filter((j) => j.league === league);
}

export function getTeamsByLeague(league: League): string[] {
  const teams = jerseys
    .filter((j) => j.league === league)
    .map((j) => j.team);
  return [...new Set(teams)];
}

export function getBestsellers(): Jersey[] {
  return jerseys.filter((j) => j.isBestseller);
}

export function getNewArrivals(): Jersey[] {
  return jerseys.filter((j) => j.isNew);
}
