import type { League, LeagueInfo, Jersey } from '../types';

export const leagues: LeagueInfo[] = [
  { id: 'la-liga', name: { en: 'La Liga', es: 'La Liga' }, country: 'ES' },
  { id: 'premier-league', name: { en: 'Premier League', es: 'Premier League' }, country: 'GB' },
  { id: 'serie-a', name: { en: 'Serie A', es: 'Serie A' }, country: 'IT' },
  { id: 'bundesliga', name: { en: 'Bundesliga', es: 'Bundesliga' }, country: 'DE' },
  { id: 'ligue-1', name: { en: 'Ligue 1', es: 'Ligue 1' }, country: 'FR' },
  { id: 'brasileirao', name: { en: 'Brasileirão', es: 'Brasileirão' }, country: 'BR' },
  { id: 'lpf-argentina', name: { en: 'LPF Argentina', es: 'LPF Argentina' }, country: 'AR' },
  { id: 'selecciones', name: { en: 'National Teams', es: 'Selecciones' }, country: 'INTL' },
];

export const jerseys: Jersey[] = [
  // La Liga
  {
    id: 'real-madrid-home',
    team: 'Real Madrid',
    league: 'la-liga',
    price: 89.99,
    originalPrice: 109.99,
    image: '/jerseys/real-madrid-home.webp',
    badge: '/badges/real-madrid.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'barcelona-home',
    team: 'FC Barcelona',
    league: 'la-liga',
    price: 89.99,
    originalPrice: 109.99,
    image: '/jerseys/barcelona-home.webp',
    badge: '/badges/barcelona.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'atletico-madrid-home',
    team: 'Atlético de Madrid',
    league: 'la-liga',
    price: 84.99,
    image: '/jerseys/atletico-home.webp',
    badge: '/badges/atletico.webp',
    variant: 'home',
    season: '2024/25',
  },
  {
    id: 'real-sociedad-home',
    team: 'Real Sociedad',
    league: 'la-liga',
    price: 79.99,
    image: '/jerseys/real-sociedad-home.webp',
    badge: '/badges/real-sociedad.webp',
    variant: 'home',
    season: '2024/25',
    isNew: true,
  },

  // Premier League
  {
    id: 'manchester-city-home',
    team: 'Manchester City',
    league: 'premier-league',
    price: 94.99,
    image: '/jerseys/man-city-home.webp',
    badge: '/badges/man-city.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'liverpool-home',
    team: 'Liverpool FC',
    league: 'premier-league',
    price: 94.99,
    originalPrice: 109.99,
    image: '/jerseys/liverpool-home.webp',
    badge: '/badges/liverpool.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'arsenal-home',
    team: 'Arsenal FC',
    league: 'premier-league',
    price: 89.99,
    image: '/jerseys/arsenal-home.webp',
    badge: '/badges/arsenal.webp',
    variant: 'home',
    season: '2024/25',
  },
  {
    id: 'chelsea-home',
    team: 'Chelsea FC',
    league: 'premier-league',
    price: 89.99,
    image: '/jerseys/chelsea-home.webp',
    badge: '/badges/chelsea.webp',
    variant: 'home',
    season: '2024/25',
    isNew: true,
  },

  // Serie A
  {
    id: 'inter-milan-home',
    team: 'Inter Milan',
    league: 'serie-a',
    price: 84.99,
    image: '/jerseys/inter-home.webp',
    badge: '/badges/inter.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'ac-milan-home',
    team: 'AC Milan',
    league: 'serie-a',
    price: 84.99,
    image: '/jerseys/ac-milan-home.webp',
    badge: '/badges/ac-milan.webp',
    variant: 'home',
    season: '2024/25',
  },
  {
    id: 'juventus-home',
    team: 'Juventus FC',
    league: 'serie-a',
    price: 84.99,
    originalPrice: 99.99,
    image: '/jerseys/juventus-home.webp',
    badge: '/badges/juventus.webp',
    variant: 'home',
    season: '2024/25',
  },
  {
    id: 'napoli-home',
    team: 'SSC Napoli',
    league: 'serie-a',
    price: 79.99,
    image: '/jerseys/napoli-home.webp',
    badge: '/badges/napoli.webp',
    variant: 'home',
    season: '2024/25',
    isNew: true,
  },

  // Bundesliga
  {
    id: 'bayern-munich-home',
    team: 'Bayern München',
    league: 'bundesliga',
    price: 89.99,
    image: '/jerseys/bayern-home.webp',
    badge: '/badges/bayern.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'dortmund-home',
    team: 'Borussia Dortmund',
    league: 'bundesliga',
    price: 84.99,
    image: '/jerseys/dortmund-home.webp',
    badge: '/badges/dortmund.webp',
    variant: 'home',
    season: '2024/25',
  },
  {
    id: 'leverkusen-home',
    team: 'Bayer Leverkusen',
    league: 'bundesliga',
    price: 79.99,
    image: '/jerseys/leverkusen-home.webp',
    badge: '/badges/leverkusen.webp',
    variant: 'home',
    season: '2024/25',
    isNew: true,
  },

  // Ligue 1
  {
    id: 'psg-home',
    team: 'Paris Saint-Germain',
    league: 'ligue-1',
    price: 94.99,
    image: '/jerseys/psg-home.webp',
    badge: '/badges/psg.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'marseille-home',
    team: 'Olympique de Marseille',
    league: 'ligue-1',
    price: 79.99,
    image: '/jerseys/marseille-home.webp',
    badge: '/badges/marseille.webp',
    variant: 'home',
    season: '2024/25',
  },

  // Brasileirão
  {
    id: 'flamengo-home',
    team: 'Flamengo',
    league: 'brasileirao',
    price: 74.99,
    image: '/jerseys/flamengo-home.webp',
    badge: '/badges/flamengo.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'palmeiras-home',
    team: 'Palmeiras',
    league: 'brasileirao',
    price: 74.99,
    image: '/jerseys/palmeiras-home.webp',
    badge: '/badges/palmeiras.webp',
    variant: 'home',
    season: '2024/25',
  },
  {
    id: 'santos-home',
    team: 'Santos FC',
    league: 'brasileirao',
    price: 69.99,
    image: '/jerseys/santos-home.webp',
    badge: '/badges/santos.webp',
    variant: 'home',
    season: '2024/25',
  },

  // LPF Argentina
  {
    id: 'boca-juniors-home',
    team: 'Boca Juniors',
    league: 'lpf-argentina',
    price: 74.99,
    image: '/jerseys/boca-home.webp',
    badge: '/badges/boca.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'river-plate-home',
    team: 'River Plate',
    league: 'lpf-argentina',
    price: 74.99,
    image: '/jerseys/river-home.webp',
    badge: '/badges/river.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'racing-club-home',
    team: 'Racing Club',
    league: 'lpf-argentina',
    price: 69.99,
    image: '/jerseys/racing-home.webp',
    badge: '/badges/racing.webp',
    variant: 'home',
    season: '2024/25',
  },
  {
    id: 'independiente-home',
    team: 'Independiente',
    league: 'lpf-argentina',
    price: 69.99,
    image: '/jerseys/independiente-home.webp',
    badge: '/badges/independiente.webp',
    variant: 'home',
    season: '2024/25',
    isNew: true,
  },

  // Selecciones
  {
    id: 'argentina-home',
    team: 'Argentina',
    league: 'selecciones',
    price: 99.99,
    image: '/jerseys/argentina-home.webp',
    badge: '/badges/argentina.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'brasil-home',
    team: 'Brasil',
    league: 'selecciones',
    price: 99.99,
    image: '/jerseys/brasil-home.webp',
    badge: '/badges/brasil.webp',
    variant: 'home',
    season: '2024/25',
    isBestseller: true,
  },
  {
    id: 'espana-home',
    team: 'España',
    league: 'selecciones',
    price: 94.99,
    image: '/jerseys/espana-home.webp',
    badge: '/badges/espana.webp',
    variant: 'home',
    season: '2024/25',
  },
  {
    id: 'francia-home',
    team: 'Francia',
    league: 'selecciones',
    price: 94.99,
    image: '/jerseys/francia-home.webp',
    badge: '/badges/francia.webp',
    variant: 'home',
    season: '2024/25',
  },
  {
    id: 'alemania-home',
    team: 'Alemania',
    league: 'selecciones',
    price: 94.99,
    image: '/jerseys/alemania-home.webp',
    badge: '/badges/alemania.webp',
    variant: 'home',
    season: '2024/25',
    isNew: true,
  },
  {
    id: 'italia-home',
    team: 'Italia',
    league: 'selecciones',
    price: 94.99,
    image: '/jerseys/italia-home.webp',
    badge: '/badges/italia.webp',
    variant: 'home',
    season: '2024/25',
  },
  {
    id: 'inglaterra-home',
    team: 'Inglaterra',
    league: 'selecciones',
    price: 94.99,
    image: '/jerseys/inglaterra-home.webp',
    badge: '/badges/inglaterra.webp',
    variant: 'home',
    season: '2024/25',
  },
];

export function getJerseysByLeague(league: League): Jersey[] {
  return jerseys.filter((j) => j.league === league);
}

export function getBestsellers(): Jersey[] {
  return jerseys.filter((j) => j.isBestseller);
}

export function getNewArrivals(): Jersey[] {
  return jerseys.filter((j) => j.isNew);
}
